<?php

return [
    'validation' => [
        'success' => 'admin_layout.json 校验已成功完成。',
        'schema_failed' => 'JSON 架构校验失败：:errors',
        'unexpected_error' => '发生意外错误：:message',
        'schema_not_found' => '找不到 JSON 架构文件：:path',
        'schema_parse_error' => 'JSON 架构文件解析错误：:error',
        'file_not_found' => '找不到文件：:path',
        'json_parse_error' => 'JSON 解析错误（:file）：:error',
        'version_unknown' => '未知版本',
        'version_error' => '无法获取版本信息',
        'module_required' => '模块名称为必填项',
        'module_string' => '模块名称必须为字符串',
        'module_format' => '模块名称必须以字母开头，且只能包含字母、数字、下划线和连字符',
        'module_max_length' => '模块名称不能超过 50 个字符',
        'log' => [
            'success' => 'admin_layout.json 校验成功',
            'failed' => 'admin_layout.json 校验失败',
            'exception' => 'admin_layout.json 校验过程中发生异常',
            'version_error' => '获取架构版本信息失败',
        ],
    ],
    'loader' => [
        'validation_failed' => '模块 :module 的布局校验失败：:errors',
        'file_not_found' => '找不到布局文件：:path',
        'json_parse_error' => 'JSON 解析错误（:file）：:error',
        'file_load_error' => '加载文件过程中发生错误（:path）：:error',
        'log' => [
            'cache_hit' => '从缓存加载布局数据',
            'cache_invalidated' => '缓存已失效',
            'loaded' => '布局文件加载完成',
            'cached' => '布局数据已存入缓存',
            'cache_manually_invalidated' => '手动使缓存失效',
            'all_cache_invalidated' => '所有缓存已失效',
            'file_load_error' => '文件加载错误',
        ],
    ],
    'command' => [
        'starting' => '开始校验 admin_layout.json 文件',
        'validating_module' => '正在校验模块 :module...',
        'validating_all_modules' => '开始校验 :count 个模块',
        'module_layout_not_found' => '找不到模块 :module 的 admin_layout.json 文件',
        'module_valid' => '模块 :module 校验成功',
        'module_invalid' => '模块 :module 校验失败：:error',
        'unexpected_error' => '模块 :module 中发生意外错误：:error',
        'modules_directory_not_found' => '找不到 modules 目录',
        'no_modules_found' => '没有可校验的模块',
        'module_summary' => '模块 :module 摘要',
        'menu_name' => '菜单名称',
        'menu_route' => '路由',
        'data_sources_count' => '数据源数量',
        'layout_type' => '布局类型',
        'validation_summary' => '校验结果摘要',
        'valid_modules_count' => '有效模块',
        'invalid_modules_count' => '无效模块',
        'missing_layouts_count' => '缺少布局文件',
        'invalid_modules_details' => '无效模块详情：',
        'missing_layouts_details' => '缺少布局文件的模块：',
        'cache_stats' => '缓存统计',
        'total_cached_modules' => '已缓存模块数',
        'cache_expiration' => '缓存过期时间',
        'cached_modules_details' => '已缓存模块详情：',
        'clearing_cache' => '正在使缓存失效...',
        'cache_cleared' => '缓存已失效',
    ],
    'success' => [
        'loaded' => '已成功加载 admin_layout.json',
        'cached' => '布局数据已存入缓存',
    ],
    'error' => [
        'module_not_found' => '找不到请求的模块',
        'json_parse_error' => 'JSON 解析过程中发生错误',
        'file_not_readable' => '无法读取文件',
        'json_parse_failed' => 'JSON 解析失败',
        'validation_failed' => '布局校验失败',
        'server_error' => '发生服务器内部错误',
    ],
    'log' => [
        'cache_hit' => '已从缓存获取布局数据',
        'cache_updated' => '缓存已更新',
        'layout_loaded' => '布局已成功加载',
        'validation_completed' => '布局校验已完成',
        'layout_load_error' => '加载布局过程中发生错误',
        'validation_error' => '校验布局过程中发生错误',
        'service_cache_invalidated' => '服务已使缓存失效',
        'service_all_cache_invalidated' => '服务已使所有缓存失效',
        'cache_invalidated' => '缓存已失效',
        'all_cache_invalidated' => '所有缓存已失效',
        'file_read_error' => '读取文件过程中发生错误',
    ],
];
