<?php

return [
    'source_type' => [
        'core' => '核心',
        'module' => '模块',
        'plugin' => '插件',
    ],
    'permission_type' => [
        'read' => '查看／下载',
        'update' => '修改',
        'delete' => '删除',
    ],
    'default_policy' => [
        'public' => '公开（所有已登录用户）',
        'owner_only' => '仅上传者／管理员',
        'read_only' => '只读',
    ],
    'validation' => [
        'file_required' => '请选择文件。',
        'file_invalid' => '不是有效的文件。',
        'file_max' => '文件大小不能超过 :maxMB。',
        'file_extension_invalid' => '不支持的文件格式。允许的格式：:extensions',
        'files_required' => '请选择文件。',
        'files_array' => '文件格式不正确。',
        'files_min' => '请至少选择 1 个文件。',
        'type_invalid' => '附件目标类型不正确。',
        'id_invalid' => '附件目标 ID 不正确。',
        'role_ids_required' => '请选择角色。',
        'role_ids_invalid' => '角色格式不正确。',
        'role_id_integer' => '角色 ID 必须为整数。',
        'role_id_exists' => '该角色不存在。',
        'order_required' => '需要排序数据。',
        'order_array' => '排序数据格式不正确。',
        'order_id_required' => '需要附件 ID。',
        'order_id_exists' => '该附件不存在。',
        'order_value_required' => '需要排序值。',
        'order_value_integer' => '排序值必须为整数。',
        'permissions_required' => '需要权限信息。',
        'permissions_invalid' => '权限格式不正确。',
        'permission_roles_invalid' => '各权限对应的角色格式不正确。',
    ],
    'upload_success' => '文件已上传。',
    'upload_batch_success' => '文件已批量上传。',
    'upload_failed' => '文件上传失败。',
    'delete_success' => '文件已删除。',
    'delete_failed' => '删除文件失败。',
    'reorder_success' => '文件排序已变更。',
    'reorder_failed' => '变更文件排序失败。',
    'sync_roles_success' => '角色已同步。',
    'sync_roles_failed' => '同步角色失败。',
    'sync_permissions_success' => '权限已同步。',
    'sync_permissions_failed' => '同步权限失败。',
    'not_found' => '找不到附件。',
    'access_denied' => '您没有访问此附件的权限。',
    'update_denied' => '您没有修改此附件的权限。',
    'delete_denied' => '您没有删除此附件的权限。',
];
