<?php

return [
    'login_success' => '登录成功。',
    'login_failed' => '认证失败。',
    'two_factor_required' => '验证码已发送。请输入收到的验证码以完成登录。',
    'two_factor_failed' => '验证码不正确或已过期。',
    'two_factor_invalid_challenge' => '找不到认证请求。请重新登录。',
    'two_factor_delivery_failed' => '验证码发送失败。请联系管理员。',
    'register_success' => '注册成功。',
    'register_failed' => '注册失败。',
    'logout_success' => '退出登录成功。',
    'logout_all_devices_success' => '已在所有设备上退出登录。',
    'password_reset_success' => '密码已成功重置。',
    'password_reset_failed' => '重置密码失败。',
    'invalid_credentials' => '认证信息有误。',
    'admin_login_success' => '管理员登录成功。',
    'admin_required' => '需要管理员权限。',
    'unauthenticated' => '需要登录认证。',
    'permission_denied' => '没有相应权限。',
    'layout_permission_denied' => '没有访问该布局的权限。（所需权限：:required_permissions）',
    'layout_guest_permission_denied' => '该布局需要登录后访问。（所需权限：:required_permissions）',
    'invalid_permission_type' => '权限类型无效。',
    'role_denied' => '没有相应角色。',
    'email_not_registered' => '该邮箱尚未注册。',
    'guest_permission_denied' => '游客无法执行该操作。请先登录。',
    'scope_denied' => '没有访问该资源的权限。',
    'scope_type_all' => '全部',
    'scope_type_self' => '仅本人',
    'scope_type_role' => '所属角色',
    'invalid_token' => '认证令牌无效。',
    'token_expired' => '认证令牌已过期。请重新登录。',
    'user_not_found' => '找不到该用户。',
    'account_inactive' => '该账号已停用。请联系管理员。',
    'account_blocked' => '该账号已被封禁。请联系管理员。',
    'account_withdrawn' => '该账号已注销。',
    'account_pending_verification' => '该账号尚未完成实名认证。请先完成邮箱验证。',
    'account_locked' => '登录尝试次数过多，账号已锁定。请在 :minutes 分钟后重试。',
    'account_locked_permanently' => '登录尝试次数过多，账号已锁定。请联系管理员。',
    'account_unlocked' => '账号锁定已解除。',
    'reset_token_invalid' => '密码重置令牌无效。',
    'reset_token_expired' => '密码重置令牌已过期。请重新申请。',
    'password_reset_email_sent' => '密码重置邮件已发送。',
    'email_send_failed' => '邮件发送失败。请稍后重试。',
];
