<?php

return [
    'cannot_delete_super_admin' => '无法删除超级管理员。',
    'cannot_modify_super_admin' => '您没有修改超级管理员账号或角色的权限。',
    'cannot_grant_unheld_permission' => '无法授予自己未持有的权限或范围更大的权限。',
    'cannot_modify_protected_role' => '您没有修改系统或扩展所拥有角色的权限。',
    'circular_reference' => '检测到布局循环引用：:trace',
    'max_depth_exceeded' => '布局嵌套深度超过了最大允许深度（:max）。',
    'template_file_copy_failed' => '复制模板文件失败：:source → :destination',
    'template_build_directory_creation_failed' => '创建模板构建目录失败：:path',
    'template_dist_directory_not_found' => '找不到模板 dist 目录：:path',
    'template_not_found' => '找不到模板：:identifier',
    'template_not_active' => '模板未启用：:identifier（状态：:status）',
    'concurrent_modification' => '其他用户已先行保存。（资源：:resource，当前版本：:current，提交版本：:expected）',
    'layout' => [
        'duplicate_data_source_id' => 'data_sources ID 重复：:id',
        'duplicate_data_source_id_in_file' => '布局文件内 data_sources ID 重复：:ids（文件：:file）',
        'duplicate_data_source_id_extends' => 'extends 继承关系中 data_sources ID 重复：:ids（子级：:child，父级：:parent）',
        'not_found' => '找不到布局：:name',
        'parent_not_found' => '找不到父级布局：:parent（请求的布局：:child）',
        'include_file_not_found' => '找不到 include 文件：:path（解析后的路径：:resolved）',
        'invalid_include_json' => 'include 文件的 JSON 格式不正确：:path（错误：:error）',
        'circular_include' => '检测到 include 循环引用：:trace',
        'max_include_depth_exceeded' => '超过 include 最大深度（最大：:max 层）',
        'include_outside_directory' => 'include 路径位于允许的目录之外：:path（允许：:allowed_dir）',
    ],
    'layout_version' => [
        'save_failed_after_retries' => '保存布局版本失败。重试 :attempts 次后仍然失败。',
        'save_failed_unexpected' => '保存布局版本过程中发生意外错误。',
    ],
    'settings' => [
        'backup_creation_failed' => '创建设置备份文件失败。',
        'restore_failed' => '恢复设置失败。',
        'category_not_found' => '找不到设置分类：:category',
        'save_failed' => '保存设置失败：:category',
        'json_parse_failed' => '解析 JSON 文件失败：:path（:error）',
        'add_category_module_only' => 'addCategory 只能在模块中使用。',
    ],
    'core_update' => [
        'handoff' => '升级交接：已完成至 :after_version — :reason（重新执行：:resume_command）',
    ],
    'vendor' => [
        'composer_not_available' => '当前环境无法执行 Composer。请使用捆绑模式。',
        'composer_not_available_for_build' => '构建 vendor-bundle 需要执行 Composer。请在开发环境中安装并配置 Composer 后重试。',
        'bundle_build_composer_failed' => '构建 vendor-bundle 时执行 composer install 失败（exit :exit）：:message',
        'bundle_build_promote_failed' => '未能将 vendor-bundle 构建结果写入最终路径（:from → :to）',
        'composer_execution_failed' => '执行 Composer 失败：:message',
        'bundle_zip_missing' => '找不到 vendor-bundle.zip 文件：:path',
        'bundle_manifest_missing' => '找不到 vendor-bundle.json 文件：:path',
        'bundle_manifest_invalid' => '无法读取 vendor-bundle.json 文件：:error',
        'bundle_integrity_failed' => '捆绑文件的完整性校验失败：:details',
        'bundle_schema_unsupported' => '不支持的 vendor-bundle.json 架构版本：:version',
        'zip_archive_not_available' => '尚未安装 PHP ZipArchive 扩展。',
        'zip_hash_mismatch' => 'vendor-bundle.zip 的哈希值不一致（期望：:expected，实际：:actual）。',
        'composer_json_sha_mismatch' => 'composer.json 在捆绑包构建之后发生了变更。请使用 vendor-bundle:build 重新构建。',
        'composer_lock_sha_mismatch' => 'composer.lock 在捆绑包构建之后发生了变更。请使用 vendor-bundle:build 重新构建。',
        'bundle_contains_unsafe_path' => '捆绑 zip 中包含不安全的文件路径：:path',
        'extraction_failed' => '解压捆绑 zip 失败：:message',
        'no_vendor_strategy_available' => '无法确定 Vendor 安装策略。Composer 与捆绑 zip 均不可用。',
        'source_dir_not_found' => '找不到安装源目录：:path',
        'target_not_writable' => '目标目录没有写入权限：:path',
        'target_not_writable_owner_hint' => "执行用户（:current_user）与目录所有者（:owner）不一致。请执行 'chown -R :current_user_name :path' 后重试，或以所有者（:owner_name）身份 SSH 登录后执行。",
        'composer_json_not_found' => '找不到 composer.json 文件：:path',
        'no_composer_lock' => '需要 composer.lock 文件。请先执行 composer install：:path',
        'vendor_dir_not_found' => 'vendor/ 目录不存在。请先执行 composer install：:path',
        'composer_binary_not_found' => '找不到 Composer 可执行文件。请设置 COMPOSER_BINARY 环境变量，或将 composer 添加到 PATH。',
    ],
    'seo' => [
        'sitemap_write_failed' => '写入 Sitemap 文件失败：:path',
        'sitemap_gzip_failed' => '压缩 Sitemap 子文件失败：:file',
        'sitemap_temp_file_unreadable' => '无法读取 Sitemap 临时文件：:file',
        'sitemap_stat_group_column_unsupported' => '不支持的分组基准列：:column',
    ],
];
