<?php

return [
    'fetch_success' => '已获取语言包列表。',
    'fetch_failed' => '加载语言包列表失败。',
    'not_found' => '找不到语言包。',
    'install_success' => '语言包已安装。',
    'install_failed' => '语言包安装失败。',
    'activate_success' => '语言包已启用。',
    'activate_failed' => '语言包启用失败。',
    'deactivate_success' => '语言包已停用。',
    'deactivate_failed' => '语言包停用失败。',
    'uninstall_success' => '语言包已卸载。',
    'uninstall_failed' => '语言包卸载失败。',
    'manifest_invalid' => 'language-pack.json 校验失败。',
    'check_updates_success' => '更新检查已完成。',
    'check_updates_failed' => '更新检查失败。',
    'update_success' => '语言包已更新。',
    'update_failed' => '语言包更新失败。',
    'refresh_cache_success' => '语言包缓存已刷新。',
    'refresh_cache_failed' => '刷新语言包缓存失败。',
    'preview_success' => 'manifest 预览已完成。',
    'preview_failed' => 'manifest 预览失败。',
    'errors' => [
        'manifest_not_found' => '在 ZIP 中找不到 language-pack.json 文件。',
        'manifest_invalid_json' => 'language-pack.json 的 JSON 格式不正确。',
        'php_outside_backend' => 'PHP 文件只能放在 backend/{语言代码}/{分组}.php 位置（:file）。',
        'php_file_not_literal_array' => 'PHP 文件只能包含翻译数组。文件 :file 第 :line 行存在非数组代码。',
        'unsupported_file_type' => '语言包中不允许该文件格式（:file — :extension）。只能包含 json、php、md 文件。',
        'symlink_not_allowed' => '语言包中不能包含符号链接（:file）。',
        'auto_activate_requires_manage' => '安装后立即启用需要语言包管理权限。取消该选项后仍可正常完成安装。',
        'core_locale_missing' => '需要先启用核心语言包（:locale）。',
        'target_not_installed' => '目标 :scope（:target）尚未安装。',
        'target_inactive' => '目标 :scope（:target）处于停用状态。请先启用。',
        'target_version_too_old' => '目标 :scope（:target）的版本不满足要求（:constraint）。',
        'downgrade_blocked' => '已阻止降级（:from → :to）。',
        'protected_pack' => '受保护的语言包无法停用或卸载。',
        'download_failed' => '未能从 URL（:url）下载语言包：:error',
        'download_url_not_public' => '无法从内网地址（私有 IP、localhost 等）下载语言包。请使用可从外部访问的 https 地址。',
        'checksum_mismatch' => '校验和不一致。',
        'update_no_source' => '缺少更新来源信息（仅 GitHub 来源的语言包可更新）。',
        'update_already_latest' => '已是最新版本。',
        'preview_invalid_manifest' => 'manifest 文件无效，预览失败。',
        'operation_in_progress' => '语言包（:identifier）上有其他操作正在进行。请在完成后重试。',
        'bundled_not_found' => '捆绑目录（lang-packs/_bundled/:identifier）不存在。',
        'slot_conflict' => '同一插槽中已有启用的语言包（:current）。若要替换为（:target），需要确认。',
        'directory_not_writable' => '语言包安装目录（:path）没有写入权限。请为 Web 服务器用户（例如 www-data）授予写入权限。（例：sudo chgrp www-data :path && sudo chmod g+w :path）',
        'identifier_not_found' => '找不到语言包（:identifier）。',
        'unsupported_source' => '不支持的来源（:source）— 请使用 bundled、github、url 之一。',
    ],
    'validation' => [
        'file_required' => '请上传语言包 ZIP 文件。',
        'file_invalid' => '上传的文件无效。',
        'file_too_large' => '文件大小不能超过 10MB。',
        'file_not_zip' => '只能上传 ZIP 格式的文件。',
        'github_url_required' => '请输入 GitHub URL。',
        'github_url_invalid' => '请输入正确的 URL。',
        'github_url_format' => '必须为 GitHub 仓库 URL 格式，例如：https://github.com/owner/repo',
        'url_required' => '请输入下载 URL。',
        'url_invalid' => '请输入正确的 URL。',
        'checksum_invalid' => 'SHA-256 校验和必须为 64 位十六进制字符。',
        'identifier_required' => '请输入语言包标识符。',
        'identifier_invalid' => '标识符只允许使用字母、数字、点、下划线和连字符。',
    ],
];
