<?php

return [
    'fetch_success' => '已成功获取菜单。',
    'fetch_failed' => '获取菜单失败。',
    'active_fetch_failed' => '获取已启用菜单失败。',
    'create_success' => '菜单已成功创建。',
    'create_failed' => '创建菜单失败。',
    'create_error' => '创建菜单过程中发生错误。',
    'update_success' => '菜单已成功更新。',
    'update_failed' => '更新菜单失败。',
    'update_error' => '更新菜单过程中发生错误。',
    'delete_success' => '菜单已成功删除。',
    'delete_failed' => '删除菜单失败。',
    'delete_error' => '删除菜单过程中发生错误。',
    'order_update_success' => '菜单排序已成功更新。',
    'order_update_failed' => '更新菜单排序失败。',
    'slug_already_exists' => '该别名已被使用。',
    'parent_menu_not_found' => '上级菜单不存在。',
    'cannot_set_self_as_parent' => '不能将自身设置为上级菜单。',
    'cannot_delete_menu_with_children' => '无法删除含有下级菜单的菜单。',
    'validation' => [
        'is_active_boolean' => '启用状态必须为真／假值。',
        'sort_by_invalid' => '排序字段无效。',
        'sort_order_invalid' => '排序方式无效。',
        'filters_array' => '筛选条件必须为数组格式。',
        'filters_max' => '最多可指定 10 个筛选条件。',
        'filter_field_required' => '筛选字段为必填项。',
        'filter_field_invalid' => '筛选字段无效。',
        'filter_value_required' => '筛选值为必填项。',
        'filter_value_max' => '筛选值最多可输入 255 个字符。',
        'filter_operator_invalid' => '筛选运算符无效。',
    ],
];
