<?php

return [
    'not_found' => '找不到模块 :module。',
    'dependency_not_active' => '依赖模块 :dependency 未安装或未启用。',
    'fetch_success' => '已成功获取模块。',
    'fetch_failed' => '获取模块失败：:error',
    'install_success' => '模块已成功安装。',
    'install_failed' => '模块安装失败：:error',
    'preview_success' => 'manifest 预览已完成。',
    'preview_failed' => 'manifest 预览失败：:error',
    'uninstall_success' => '模块已成功卸载。',
    'uninstall_failed' => '模块卸载失败：:error',
    'activate_success' => '模块已成功启用。',
    'activate_failed' => '模块启用失败：:error',
    'deactivate_success' => '模块已成功停用。',
    'deactivate_failed' => '模块停用失败：:error',
    'update_success' => '模块已成功更新。',
    'update_failed' => '模块更新失败：:error',
    'refresh_layouts_success' => '模块布局已成功刷新。',
    'refresh_layouts_failed' => '刷新模块布局失败：:error',
    'uninstall_info_success' => '已成功获取模块卸载信息。',
    'uninstall_info_failed' => '获取模块卸载信息失败：:error',
    'dependent_templates_success' => '已成功获取依赖模板信息。',
    'dependent_templates_failed' => '获取依赖模板信息失败：:error',
    'license_not_found' => '找不到模块许可证文件。',
    'status' => [
        'active' => '已启用',
        'inactive' => '已停用',
        'installing' => '安装中',
        'uninstalling' => '卸载中',
    ],
    'errors' => [
        'module_class_not_found' => '找不到模块类。',
        'migration_failed' => '执行数据库迁移失败：:error',
        'dependency_check_failed' => '依赖检查失败：:error',
        'database_error' => '发生数据库错误。',
        'module_not_found' => '找不到模块 :name。',
        'module_not_active' => '模块 :name 未启用。',
    ],
];
