<?php

return [
    'not_found' => '找不到模块 ":module"。',
    'dependency_not_active' => '依赖模块 ":dependency" 未安装或处于停用状态。',
    'status' => [
        'active' => '已启用',
        'inactive' => '已停用',
        'updating' => '更新中',
    ],
    'commands' => [
        'list' => [
            'headers' => [
                'identifier' => '标识符',
                'name' => '名称',
                'vendor' => '厂商',
                'version' => '版本',
                'status' => '状态',
            ],
            'status' => [
                'active' => '已启用',
                'inactive' => '已停用',
                'uninstalled' => '未安装',
            ],
            'no_modules' => '没有模块。',
            'summary' => '共 :total 个模块（已安装：:installed，已启用：:active）',
            'invalid_status' => '状态无效。(installed, uninstalled, active, inactive)',
        ],
        'install' => [
            'success' => '模块 ":module" 安装完成',
            'vendor' => '厂商：:vendor',
            'version' => '版本：:version',
            'roles_created' => '已创建 :count 个角色',
            'permissions_created' => '已创建 :count 个权限',
            'menus_created' => '已创建 :count 个菜单',
            'already_installed' => '模块 ":module" 已安装。',
            'force_reinstall' => '正在强制重新安装模块 ":module"（覆盖启用目录）...',
        ],
        'activate' => [
            'success' => '模块 ":module" 启用完成',
            'not_installed' => '模块 ":module" 未安装。',
            'already_active' => '模块 ":module" 已处于启用状态。',
            'layouts_registered' => '已注册 :count 个布局',
        ],
        'deactivate' => [
            'success' => '模块 ":module" 停用完成',
            'not_installed' => '模块 ":module" 未安装。',
            'not_active' => '模块 ":module" 未处于启用状态。',
            'warning' => '该模块的路由和功能已停用。',
            'layouts_deleted' => '已删除 :count 个布局',
        ],
        'uninstall' => [
            'success' => '模块 ":module" 删除完成',
            'roles_deleted' => '已删除 :count 个角色',
            'permissions_deleted' => '已删除 :count 个权限',
            'menus_deleted' => '已删除 :count 个菜单',
            'layouts_deleted' => '已删除 :count 个布局',
            'confirm_prompt' => '确定要删除模块 ":module" 吗？',
            'confirm_details' => [
                'roles' => '- 将删除 :count 个角色。',
                'permissions' => '- 将删除 :count 个权限。',
                'menus' => '- 将删除 :count 个菜单。',
                'layouts' => '- 将删除 :count 个布局。',
                'data' => '- 将删除该模块的所有数据。',
            ],
            'confirm_question' => '确定要删除吗？',
            'aborted' => '已取消删除模块。',
            'not_installed' => '模块 ":module" 未安装。',
        ],
        'cache_clear' => [
            'clearing_all' => '正在删除所有模块缓存...',
            'clearing_single' => '正在删除模块 ":module" 的缓存...',
            'success_all' => '模块缓存删除完成（:count 个条目）',
            'success_single' => '模块 ":module" 缓存删除完成（:count 个条目）',
        ],
        'check_updates' => [
            'not_installed' => '模块 ":module" 未安装。',
            'no_installed' => '没有已安装的模块。',
            'update_available' => '可更新',
            'up_to_date' => '最新',
            'headers' => [
                'identifier' => '标识符',
                'current_version' => '当前版本',
                'latest_version' => '最新版本',
                'source' => '来源',
                'status' => '状态',
            ],
            'summary' => '共检查 :total 个（可更新：:updates 个）',
            'single_up_to_date' => '模块 ":module" 已是最新版本。(v:version)',
            'single_update_available' => '模块 ":module" 可更新：v:current → v:latest (:source)',
        ],
        'update' => [
            'success' => '模块 ":module" 更新完成',
            'version_change' => 'v:from → v:to',
            'no_update' => '模块 ":module" 没有可用的更新。',
            'not_installed' => '模块 ":module" 未安装。',
            'current_version' => '当前版本：:version',
            'latest_version' => '最新版本：:version',
            'update_source' => '更新来源：:source',
            'confirm_question' => '是否继续更新？',
            'aborted' => '已取消更新。',
            'backup_restored' => '已从备份恢复到先前版本。',
            'force_mode' => '强制更新模式：跳过版本比较并重新安装。',
            'layout_strategy' => '布局策略：:strategy',
            'modified_extensions_warning' => '管理员编辑过的 :count 项布局扩展将被覆盖。',
            'modified_extension_item' => '  - :target（来源：:source）',
        ],
    ],
    'composer_install' => [
        'start' => '正在安装模块 ":module" 的 Composer 依赖...',
        'success' => '模块 ":module" 的 Composer 依赖安装完成',
        'no_dependencies' => '模块 ":module" 没有需要安装的 Composer 依赖。',
        'failed' => '模块 ":module" 的 Composer 依赖安装失败。',
        'summary' => '📊 结果：成功 :success 个，跳过 :skip 个，失败 :fail 个',
    ],
    'update_success' => '模块 ":module" 已更新至 :version 版本。',
    'update_failed' => '模块更新失败：:error',
    'update_hook_failed' => '执行模块更新钩子失败：:error',
    'no_update_available' => '没有可更新的内容。',
    'check_updates_success' => '更新检查已完成。',
    'check_updates_failed' => '更新检查失败：:error',
    'check_modified_layouts_success' => '已修改布局的检查已完成。',
    'check_modified_layouts_failed' => '检查已修改的布局失败：:error',
    'not_installed' => '模块 ":module" 未安装。',
    'pending_not_found' => '在待安装列表中找不到模块 ":module"。',
    'already_exists' => '模块 ":module" 已存在。',
    'move_failed' => '移动模块 ":module" 失败：:error',
    'deactivate_warning' => '有已启用的模板依赖此模块。',
    'installation_failed' => '模块安装失败：:error',
    'activation_failed' => '模块启用失败：:error',
    'deactivation_failed' => '模块停用失败：:error',
    'uninstallation_failed' => '模块卸载失败：:error',
    'refresh_layouts_failed' => '刷新布局失败：:error',
    'warnings' => [
        'has_dependent_templates' => '有已启用的模板依赖此模块。如需停用，请使用强制选项。',
        'has_dependents' => '有已启用的扩展依赖此模块。',
        'deactivation_warning' => '停用后，以下模板将受到影响：',
        'confirm_deactivation' => '仍要停用吗？',
        'missing_dependencies' => '启用此模块需要以下依赖。',
    ],
    'activate_warning' => '启用模块所需的依赖尚未满足。',
    'deactivate_warning_extended' => '有已启用的扩展（模板、模块、插件）依赖此模块。',
    'errors' => [
        'force_update_no_source' => '找不到可用于强制更新 :module 的来源。捆绑包和 GitHub URL 均不存在。',
        'downgrade_blocked' => '已阻止降级（:from → :to）。如需有意降级，请使用 --force 选项。',
        'zip_open_failed' => '无法打开 ZIP 文件：:error',
        'module_json_not_found' => '找不到 module.json 文件。',
        'module_json_invalid' => 'module.json 文件格式不正确。',
        'identifier_missing' => '缺少模块标识符。',
        'already_installed' => '该模块已安装。',
        'install_failed' => '模块安装失败：:error',
        'github_url_invalid' => 'GitHub URL 格式无效。',
        'github_download_failed' => '从 GitHub 下载失败：:error',
        'github_repo_not_found' => '找不到 GitHub 仓库。',
        'module_not_found' => '找不到模块 :name。',
        'module_not_active' => '模块 :name 未启用。',
        'not_found' => '找不到模块 :module。',
        'file_not_found' => '找不到文件。',
        'file_type_not_allowed' => '不允许的文件格式。',
        'unknown_error' => '发生未知错误。',
        'invalid_permission_structure' => '模块 ":identifier" 的权限结构不正确：:reason',
        'invalid_translation_path' => '模块 ":identifier" 的语言文件路径不正确。应使用 ":correct_path" 而非 ":wrong_path"。',
        'seo_variable_conflict' => '模块 ":identifier" 的 SEO 变量名与已有扩展冲突：:reason',
        'layout_validation_json_error' => '布局文件 :file 的 JSON 解析失败：:error',
        'layout_validation_missing_name' => '布局文件 :file 中缺少 layout_name。',
        'layout_validation_partial_error' => '布局文件 :file 的 partial 处理失败：:error (partial: :partial)',
        'layout_validation_validation_failed' => '模块 :identifier 的布局校验失败。共发现 :count 个错误：:error',
        'operation_in_progress' => '模块 ":name" 当前处于 :status 状态。请等待操作完成。',
        'github_api_failed' => '调用 GitHub API 失败：:error',
        'invalid_github_url' => 'GitHub URL 无效。',
        'zip_url_not_found' => '找不到 ZIP 下载 URL。',
        'download_failed' => '下载模块 ":module" :version 版本失败：:error',
        'zip_extract_failed' => 'ZIP 解压失败：:error',
        'extracted_dir_not_found' => '找不到解压后的目录。',
        'reload_failed' => '重新加载模块失败：:error',
        'delete_directory_failed' => '删除模块目录失败：:error',
        'update_failed' => '模块 ":module" 更新失败：:error',
        'invalid_layout_strategy' => '布局策略无效。(仅允许 overwrite 或 keep)',
        'invalid_vendor_mode' => 'Vendor 安装模式无效。(仅允许 auto、composer、bundled)',
    ],
    'validation' => [
        'name_required' => '模块名称为必填项。',
        'name_string' => '模块名称必须为字符串。',
        'name_max' => '模块名称不能超过 255 个字符。',
        'search_max' => '搜索词不能超过 255 个字符。',
        'filters_max' => '搜索条件最多可指定 10 个。',
        'filter_field_required' => '搜索字段为必填项。',
        'filter_field_invalid' => '搜索字段无效。',
        'filter_value_required' => '搜索值为必填项。',
        'filter_value_max' => '搜索值不能超过 255 个字符。',
        'filter_operator_invalid' => '搜索运算符无效。',
        'status_invalid' => '状态无效。',
        'per_page_min' => '每页条数最少为 1 个。',
        'per_page_max' => '每页条数最多为 100 个。',
        'page_min' => '页码最小为 1。',
        'file_required' => '模块文件为必填项。',
        'file_invalid' => '不是有效的文件。',
        'file_must_be_zip' => '模块文件必须为 ZIP 格式。',
        'file_max_size' => '模块文件大小不能超过 :sizeMB。',
        'github_url_required' => 'GitHub URL 为必填项。',
        'github_url_invalid' => 'URL 格式无效。',
        'github_url_format' => 'GitHub 仓库 URL 格式不正确。',
        'with_max' => 'with 参数最多可指定 10 个。',
        'with_invalid' => 'with 关联无效。',
    ],
];
