<?php

return [
    'definition_list_success' => '已获取通知定义列表。',
    'definition_list_failed' => '获取通知定义列表失败。',
    'definition_show_success' => '已获取通知定义。',
    'definition_show_failed' => '获取通知定义失败。',
    'definition_updated' => '通知定义已修改。',
    'definition_update_failed' => '修改通知定义失败。',
    'definition_toggled' => '通知定义的启用状态已变更。',
    'definition_toggle_failed' => '变更通知定义的启用状态失败。',
    'definition_not_found' => '找不到通知定义。',
    'definition_reset' => '通知定义的所有模板已恢复为默认值。',
    'definition_reset_failed' => '重置通知定义失败。',
    'channel_skipped_no_template' => ':channel 渠道中没有 :type 类型的启用模板，已跳过发送。',
    'channel_disabled_by_extension' => '该渠道在扩展的系统设置中已被停用，已跳过发送。',
    'channel_guest_not_allowed' => '该渠道不允许向游客发送，已跳过发送。',
    'template_updated' => '通知模板已修改。',
    'template_update_failed' => '修改通知模板失败。',
    'template_toggled' => '通知模板的启用状态已变更。',
    'template_toggle_failed' => '变更通知模板的启用状态失败。',
    'template_reset' => '通知模板已恢复为默认值。',
    'template_reset_failed' => '恢复通知模板默认值失败。',
    'template_inactive' => '该渠道的通知模板处于停用状态。',
    'template_not_found' => '找不到该渠道的通知模板。',
    'default_data_not_found' => '找不到默认模板数据。',
    'preview_success' => '已生成预览。',
    'preview_failed' => '生成预览失败。',
    'channels_success' => '已获取通知渠道列表。',
    'channels_failed' => '获取通知渠道列表失败。',
    'definition' => '通知定义',
    'subject' => '标题',
    'body' => '正文',
    'readiness' => [
        'mail_from_address_not_configured' => '尚未设置发件人邮箱。',
        'mail_smtp_host_empty' => '尚未设置 SMTP 主机。',
        'mail_smtp_port_empty' => '尚未设置 SMTP 端口。',
        'mail_mailgun_domain_empty' => '尚未设置 Mailgun 域名。',
        'mail_mailgun_secret_empty' => '尚未设置 Mailgun 密钥。',
        'mail_ses_key_empty' => '尚未设置 SES Key。',
        'mail_ses_secret_empty' => '尚未设置 SES 密钥。',
        'database_table_missing' => '通知数据表不存在。',
        'unknown' => '渠道设置尚未完成。',
    ],
    'user' => [
        'list_success' => '已获取通知列表。',
        'list_failed' => '获取通知列表失败。',
        'unread_count_success' => '已获取未读通知数量。',
        'unread_count_failed' => '获取未读通知数量失败。',
        'read_success' => '通知已标记为已读。',
        'read_failed' => '将通知标记为已读失败。',
        'read_all_success' => '所有通知已标记为已读。',
        'read_all_failed' => '全部标记为已读失败。',
        'delete_success' => '通知已删除。',
        'delete_failed' => '删除通知失败。',
        'delete_all_success' => '所有通知已删除。',
        'delete_all_failed' => '删除全部通知失败。',
        'not_found' => '找不到通知。',
    ],
    'channels' => [
        'core_default' => '核心默认渠道',
        'mail' => [
            'name' => '邮件',
            'description' => '通过电子邮件发送通知',
        ],
        'database' => [
            'name' => '站内通知',
            'description' => '在站内通知中心显示',
        ],
    ],
];
