<?php

return [
    'list_success' => '已成功获取插件列表。',
    'list_failed' => '获取插件列表失败：:error',
    'fetch_success' => '已成功获取插件信息。',
    'fetch_failed' => '获取插件信息失败：:error',
    'not_found' => '找不到插件 :plugin。',
    'install_success' => '插件已成功安装。',
    'install_failed' => '插件安装失败：:error',
    'preview_success' => 'manifest 预览已完成。',
    'preview_failed' => 'manifest 预览失败：:error',
    'install_validation_failed' => '插件安装校验失败：:error',
    'install_error' => '插件安装过程中发生错误。',
    'uninstall_success' => '插件已成功卸载。',
    'uninstall_failed' => '插件卸载失败：:error',
    'uninstall_validation_failed' => '插件卸载校验失败：:error',
    'uninstall_error' => '插件卸载过程中发生错误。',
    'activate_success' => '插件已成功启用。',
    'activate_failed' => '插件启用失败：:error',
    'activate_validation_failed' => '插件启用校验失败：:error',
    'activate_error' => '插件启用过程中发生错误。',
    'deactivate_success' => '插件已成功停用。',
    'deactivate_failed' => '插件停用失败：:error',
    'deactivate_validation_failed' => '插件停用校验失败：:error',
    'deactivate_error' => '插件停用过程中发生错误。',
    'refresh_layouts_success' => '插件布局已成功刷新。',
    'refresh_layouts_failed' => '刷新插件布局失败：:error',
    'uninstall_info_success' => '已成功获取插件卸载信息。',
    'uninstall_info_failed' => '获取插件卸载信息失败：:error',
    'dependent_templates_success' => '已成功获取依赖模板信息。',
    'dependent_templates_failed' => '获取依赖模板信息失败：:error',
    'license_not_found' => '找不到插件许可证文件。',
    'refresh_layouts_validation_failed' => '插件布局刷新校验失败：:error',
    'refresh_layouts_error' => '刷新插件布局过程中发生错误。',
    'status' => [
        'active' => '已启用',
        'inactive' => '已停用',
        'updating' => '更新中',
    ],
    'update_success' => '插件 ":plugin" 已更新至 :version 版本。',
    'update_failed' => '插件更新失败：:error',
    'update_hook_failed' => '执行插件更新钩子失败：:error',
    'no_update_available' => '没有可更新的内容。',
    'check_updates_success' => '更新检查已完成。',
    'check_updates_failed' => '更新检查失败：:error',
    'check_modified_layouts_success' => '已修改布局的检查已完成。',
    'check_modified_layouts_failed' => '检查已修改的布局失败：:error',
    'not_installed' => '插件 ":plugin" 未安装。',
    'pending_not_found' => '在待安装列表中找不到插件 ":plugin"。',
    'already_exists' => '插件 ":plugin" 已存在。',
    'move_failed' => '移动插件 ":plugin" 失败：:error',
    'dependency_not_active' => '依赖项 ":dependency" 未安装或处于停用状态。',
    'installation_failed' => '插件安装失败：:error',
    'activation_failed' => '插件启用失败：:error',
    'deactivation_failed' => '插件停用失败：:error',
    'uninstallation_failed' => '插件卸载失败：:error',
    'warnings' => [
        'has_dependent_templates' => '有已启用的模板依赖此插件。如需停用，请使用强制选项。',
        'has_dependents' => '有已启用的扩展依赖此插件。',
        'deactivation_warning' => '停用后，以下模板将受到影响：',
        'confirm_deactivation' => '仍要停用吗？',
        'missing_dependencies' => '启用此插件需要以下依赖。',
    ],
    'activate_warning' => '启用插件所需的依赖尚未满足。',
    'deactivate_warning' => '有已启用的扩展依赖此插件。',
    'deactivate_warning_extended' => '有已启用的扩展（模板、模块、插件）依赖此插件。',
    'errors' => [
        'force_update_no_source' => '找不到可用于强制更新 :plugin 的来源。捆绑包和 GitHub URL 均不存在。',
        'downgrade_blocked' => '已阻止降级（:from → :to）。如需有意降级，请使用 --force 选项。',
        'invalid_permission_structure' => '插件 ":identifier" 的权限结构不正确：:reason',
        'invalid_translation_path' => '插件 ":identifier" 的语言文件路径不正确。应使用 ":correct_path" 而非 ":wrong_path"。',
        'seo_variable_conflict' => '插件 ":identifier" 的 SEO 变量名与已有扩展冲突：:reason',
        'plugin_not_found' => '找不到插件 ":name"。',
        'plugin_not_active' => '插件 ":name" 未处于启用状态。',
        'not_found' => '找不到插件 :plugin。',
        'file_not_found' => '找不到文件。',
        'file_type_not_allowed' => '不允许的文件格式。',
        'unknown_error' => '发生未知错误。',
        'layout_validation_json_error' => '布局文件 :file 的 JSON 解析失败：:error',
        'layout_validation_missing_name' => '布局文件 :file 中缺少 layout_name。',
        'layout_validation_partial_error' => '布局文件 :file 的 partial 处理失败：:error (partial: :partial)',
        'layout_validation_validation_failed' => '插件 :identifier 的布局校验失败。共发现 :count 个错误：:error',
        'operation_in_progress' => '插件 ":name" 当前处于 :status 状态。请等待操作完成。',
        'github_api_failed' => '调用 GitHub API 失败：:error',
        'invalid_github_url' => 'GitHub URL 无效。',
        'zip_url_not_found' => '找不到 ZIP 下载 URL。',
        'download_failed' => '下载插件 ":plugin" :version 版本失败：:error',
        'zip_extract_failed' => 'ZIP 解压失败：:error',
        'extracted_dir_not_found' => '找不到解压后的目录。',
        'reload_failed' => '重新加载插件失败：:error',
        'delete_directory_failed' => '删除插件目录失败：:error',
        'update_failed' => '插件 ":plugin" 更新失败：:error',
        'invalid_layout_strategy' => '布局策略无效。(仅允许 overwrite 或 keep)',
        'invalid_vendor_mode' => 'Vendor 安装模式无效。(仅允许 auto、composer、bundled)',
        'github_url_invalid' => 'GitHub URL 格式无效。',
        'github_download_failed' => '从 GitHub 下载失败：:error',
        'github_repo_not_found' => '找不到 GitHub 仓库。',
        'zip_open_failed' => '无法打开 ZIP 文件：:error',
        'plugin_json_not_found' => '找不到 plugin.json 文件。',
        'plugin_json_invalid' => 'plugin.json 文件格式不正确。',
        'identifier_missing' => '缺少插件标识符。',
        'already_installed' => '插件 ":plugin" 已安装。',
        'install_failed' => '插件安装失败：:error',
    ],
    'commands' => [
        'list' => [
            'headers' => [
                'identifier' => '标识符',
                'name' => '名称',
                'vendor' => '厂商',
                'version' => '版本',
                'status' => '状态',
            ],
            'status' => [
                'active' => '已启用',
                'inactive' => '已停用',
                'uninstalled' => '未安装',
            ],
            'no_plugins' => '没有插件。',
            'summary' => '共 :total 个插件（已安装：:installed，已启用：:active）',
            'invalid_status' => '状态无效。(installed, uninstalled, active, inactive)',
        ],
        'install' => [
            'success' => '插件 ":plugin" 安装完成',
            'vendor' => '厂商：:vendor',
            'version' => '版本：:version',
            'roles_created' => '已创建 :count 个角色',
            'permissions_created' => '已创建 :count 个权限',
            'already_installed' => '插件 ":plugin" 已安装。',
            'force_reinstall' => '正在强制重新安装插件 ":plugin"（覆盖启用目录）...',
        ],
        'activate' => [
            'success' => '插件 ":plugin" 启用完成',
            'not_installed' => '插件 ":plugin" 未安装。',
            'already_active' => '插件 ":plugin" 已处于启用状态。',
            'layouts_registered' => '已注册 :count 个布局',
        ],
        'deactivate' => [
            'success' => '插件 ":plugin" 停用完成',
            'not_installed' => '插件 ":plugin" 未安装。',
            'not_active' => '插件 ":plugin" 未处于启用状态。',
            'warning' => '该插件的路由和功能已停用。',
            'layouts_deleted' => '已删除 :count 个布局',
        ],
        'uninstall' => [
            'success' => '插件 ":plugin" 删除完成',
            'roles_deleted' => '已删除 :count 个角色',
            'permissions_deleted' => '已删除 :count 个权限',
            'layouts_deleted' => '已删除 :count 个布局',
            'confirm_prompt' => '确定要删除插件 ":plugin" 吗？',
            'confirm_details' => [
                'roles' => '- 将删除 :count 个角色。',
                'permissions' => '- 将删除 :count 个权限。',
                'layouts' => '- 将删除 :count 个布局。',
                'data' => '- 将删除该插件的所有数据。',
            ],
            'confirm_question' => '确定要删除吗？',
            'aborted' => '已取消删除插件。',
            'not_installed' => '插件 ":plugin" 未安装。',
        ],
        'cache_clear' => [
            'clearing_all' => '正在删除所有插件缓存...',
            'clearing_single' => '正在删除插件 ":plugin" 的缓存...',
            'success_all' => '插件缓存删除完成（:count 个条目）',
            'success_single' => '插件 ":plugin" 缓存删除完成（:count 个条目）',
        ],
        'check_updates' => [
            'not_installed' => '插件 ":plugin" 未安装。',
            'no_installed' => '没有已安装的插件。',
            'update_available' => '可更新',
            'up_to_date' => '最新',
            'headers' => [
                'identifier' => '标识符',
                'current_version' => '当前版本',
                'latest_version' => '最新版本',
                'source' => '来源',
                'status' => '状态',
            ],
            'summary' => '共检查 :total 个（可更新：:updates 个）',
            'single_up_to_date' => '插件 ":plugin" 已是最新版本。(v:version)',
            'single_update_available' => '插件 ":plugin" 可更新：v:current → v:latest (:source)',
        ],
        'update' => [
            'success' => '插件 ":plugin" 更新完成',
            'version_change' => 'v:from → v:to',
            'no_update' => '插件 ":plugin" 没有可用的更新。',
            'not_installed' => '插件 ":plugin" 未安装。',
            'current_version' => '当前版本：:version',
            'latest_version' => '最新版本：:version',
            'update_source' => '更新来源：:source',
            'confirm_question' => '是否继续更新？',
            'aborted' => '已取消更新。',
            'backup_restored' => '已从备份恢复到先前版本。',
            'force_mode' => '强制更新模式：跳过版本比较并重新安装。',
            'layout_strategy' => '布局策略：:strategy',
            'modified_extensions_warning' => '管理员编辑过的 :count 项布局扩展将被覆盖。',
            'modified_extension_item' => '  - :target（来源：:source）',
        ],
    ],
    'composer_install' => [
        'start' => '正在安装插件 ":plugin" 的 Composer 依赖...',
        'success' => '插件 ":plugin" 的 Composer 依赖安装完成',
        'no_dependencies' => '插件 ":plugin" 没有需要安装的 Composer 依赖。',
        'failed' => '插件 ":plugin" 的 Composer 依赖安装失败。',
        'summary' => '📊 结果：成功 :success 个，跳过 :skip 个，失败 :fail 个',
    ],
    'settings' => [
        'update_failed' => '插件设置更新失败：:error',
        'updated' => '插件设置已成功更新。',
    ],
    'validation' => [
        'github_url_required' => 'GitHub URL 为必填项。',
        'github_url_invalid' => 'URL 格式无效。',
        'github_url_format' => '必须为 GitHub 仓库 URL 格式，例如：https://github.com/owner/repo',
        'file_required' => '请选择要安装的文件。',
        'file_invalid' => '不是有效的文件。',
        'file_must_be_zip' => '只能上传 ZIP 文件。',
        'file_max_size' => '文件大小不能超过 :sizeMB。',
        'plugin_name_required' => '插件名称为必填项。',
        'plugin_name_string' => '插件名称必须为字符串。',
        'plugin_name_max' => '插件名称最多可输入 :max 个字符。',
        'name_required' => '插件名称为必填项。',
        'name_string' => '插件名称必须为字符串。',
        'name_max' => '插件名称最多可输入 255 个字符。',
        'search_max' => '搜索词最多可输入 255 个字符。',
        'filters_max' => '搜索条件最多可设置 10 个。',
        'filter_field_required' => '搜索字段为必填项。',
        'filter_field_invalid' => '搜索字段无效。',
        'filter_value_required' => '搜索值为必填项。',
        'filter_value_max' => '搜索值最多可输入 255 个字符。',
        'filter_operator_invalid' => '搜索运算符无效。',
        'status_invalid' => '状态值无效。',
        'per_page_min' => '每页条数至少为 1 个。',
        'per_page_max' => '每页条数最多可设置 100 个。',
        'page_min' => '页码至少为 1。',
    ],
];
