<?php

return [
    'fetch_success' => '已获取计划任务列表。',
    'fetch_failed' => '获取计划任务列表失败。',
    'create_success' => '计划任务已创建。',
    'create_failed' => '创建计划任务失败。',
    'update_success' => '计划任务已修改。',
    'update_failed' => '修改计划任务失败。',
    'delete_success' => '计划任务已删除。',
    'delete_failed' => '删除计划任务失败。',
    'run_success' => '计划任务已执行。',
    'run_failed' => '执行计划任务失败。',
    'duplicate_success' => '计划任务已复制。',
    'duplicate_failed' => '复制计划任务失败。',
    'bulk_status_updated' => '所选计划任务的状态已变更。',
    'bulk_update_status_failed' => '批量变更计划任务状态失败。',
    'bulk_delete_success' => '所选计划任务已删除。',
    'bulk_delete_failed' => '批量删除计划任务失败。',
    'statistics_success' => '已获取计划任务统计。',
    'statistics_failed' => '获取计划任务统计失败。',
    'history_fetch_success' => '已获取执行记录。',
    'history_fetch_failed' => '获取执行记录失败。',
    'history_delete_success' => '执行记录已删除。',
    'history_delete_failed' => '删除执行记录失败。',
    'history_not_found' => '找不到执行记录。',
    'copy' => '副本',
    'shell_command_failed' => '执行 Shell 命令失败。',
    'http_request_failed' => 'HTTP 请求失败（状态：:status）',
    'url_not_public' => '无法调用内网地址（私有 IP、localhost 等）。如需调用内网地址，请在“系统设置 > 安全”中开启“允许调用内网地址”。',
    'shell_not_allowed' => '不允许的 Shell 命令。只能将服务器上已登记的可执行文件设为计划任务运行。',
    'artisan_not_allowed' => '出于安全考虑，此 Artisan 命令不能作为计划任务运行。',
    'type' => [
        'artisan' => 'Artisan 命令',
        'shell' => 'Shell 命令',
        'url' => 'URL 调用',
    ],
    'frequency' => [
        'everyMinute' => '每分钟',
        'hourly' => '每小时',
        'daily' => '每天',
        'weekly' => '每周',
        'monthly' => '每月',
        'custom' => '自定义',
    ],
    'result' => [
        'success' => '成功',
        'failed' => '失败',
        'running' => '执行中',
        'never' => '未执行',
    ],
    'trigger_type' => [
        'scheduled' => '定时执行',
        'manual' => '手动执行',
    ],
    'duration' => [
        'seconds' => '秒',
        'minutes' => '分',
    ],
    'validation' => [
        'page_integer' => '页码必须为整数。',
        'page_min' => '页码必须大于或等于 1。',
        'per_page_integer' => '每页条数必须为整数。',
        'per_page_min' => '每页条数必须大于或等于 1。',
        'per_page_max' => '每页条数必须小于或等于 100。',
        'type_invalid' => '任务类型无效。',
        'frequency_invalid' => '执行周期无效。',
        'status_invalid' => '状态无效。',
        'last_result_invalid' => '执行结果无效。',
        'history_status_invalid' => '记录状态无效。',
        'trigger_type_invalid' => '触发类型无效。',
        'created_from_invalid' => '起始日期格式不正确。',
        'created_to_invalid' => '结束日期格式不正确。',
        'created_to_after_from' => '结束日期必须晚于起始日期。',
        'started_from_invalid' => '起始日期格式不正确。',
        'started_to_invalid' => '结束日期格式不正确。',
        'started_to_after_from' => '结束日期必须晚于起始日期。',
        'sort_by_invalid' => '排序字段无效。',
        'sort_order_invalid' => '排序方式无效。',
        'name_required' => '任务名称为必填项。',
        'name_max' => '任务名称不能超过 255 个字符。',
        'type_required' => '任务类型为必填项。',
        'command_required' => '命令为必填项。',
        'command_max' => '命令不能超过 2000 个字符。',
        'expression_required' => 'Cron 表达式为必填项。',
        'expression_max' => 'Cron 表达式不能超过 100 个字符。',
        'frequency_required' => '执行周期为必填项。',
        'timeout_integer' => '超时时间必须为整数。',
        'timeout_min' => '超时时间必须大于或等于 1 秒。',
        'timeout_max' => '超时时间必须小于或等于 86400 秒（24 小时）。',
        'ids_required' => 'ID 列表为必填项。',
        'ids_array' => 'ID 列表必须为数组。',
        'ids_min' => '至少需要 1 个 ID。',
        'id_integer' => 'ID 必须为整数。',
        'id_exists' => '该计划任务不存在。',
        'is_active_required' => '启用状态为必填项。',
        'is_active_boolean' => '启用状态必须为真／假。',
    ],
    'permissions' => [
        'read' => '查看计划任务',
        'create' => '创建计划任务',
        'update' => '修改计划任务',
        'delete' => '删除计划任务',
        'run' => '执行计划任务',
    ],
];
