<?php

return [
    'cache_cleared_all' => 'SEO 缓存已全部清空。',
    'cache_cleared_layout' => '已删除 :layout 布局的 SEO 缓存 :count 条。',
    'warmup_started' => '开始预热 SEO 缓存。',
    'warmup_started_layout' => '开始预热 :layout 布局的 SEO 缓存。',
    'warmup_dispatched' => 'SEO 缓存预热已启动。',
    'sitemap_regenerated' => 'Sitemap 重新生成已完成。',
    'sitemap_regenerate_dispatched' => '已开始重新生成 Sitemap。完成可能需要一些时间。',
    'sitemap_regenerate_failed' => '重新生成 Sitemap 失败。',
    'sitemap_disabled' => 'Sitemap 生成已禁用。',
    'sitemap_not_ready' => 'Sitemap 正在准备中。请稍后重试。',
    'sitemap_generate_failed' => '生成 Sitemap 失败：:error',
    'stats_period' => '最近 :days 天的 SEO 缓存统计',
    'stats_overall' => '总体统计',
    'stats_metric' => '项目',
    'stats_value' => '值',
    'stats_total_entries' => '缓存条目总数',
    'stats_hits' => '缓存命中',
    'stats_misses' => '缓存未命中',
    'stats_hit_rate' => '命中率',
    'stats_avg_response_time' => '平均响应时间',
    'stats_by_layout' => '按布局统计',
    'stats_layout_name' => '布局',
    'stats_total' => '合计',
    'stats_by_module' => '按模块统计',
    'stats_module_identifier' => '模块',
];
