<?php

return [
    'accepted' => ':attribute 字段必须接受。',
    'accepted_if' => '当 :other 为 :value 时，:attribute 字段必须接受。',
    'active_url' => ':attribute 字段必须是有效的 URL。',
    'after' => ':attribute 字段必须是 :date 之后的日期。',
    'after_or_equal' => ':attribute 字段必须是 :date 之后或相同的日期。',
    'alpha' => ':attribute 字段只能包含字母。',
    'alpha_dash' => ':attribute 字段只能包含字母、数字、短横线和下划线。',
    'alpha_num' => ':attribute 字段只能包含字母和数字。',
    'array' => ':attribute 字段必须是数组。',
    'ascii' => ':attribute 字段只能包含单字节字母数字字符和符号。',
    'before' => ':attribute 字段必须是 :date 之前的日期。',
    'before_or_equal' => ':attribute 字段必须是 :date 之前或相同的日期。',
    'between' => [
        'array' => ':attribute 字段必须包含 :min ~ :max 个项目。',
        'file' => ':attribute 字段必须在 :min ~ :max KB 之间。',
        'numeric' => ':attribute 字段必须在 :min ~ :max 之间。',
        'string' => ':attribute 字段必须在 :min ~ :max 个字符之间。',
    ],
    'boolean' => ':attribute 字段必须为 true 或 false。',
    'can' => ':attribute 字段包含不被允许的值。',
    'confirmed' => ':attribute 字段的确认不匹配。',
    'contains' => ':attribute 字段缺少必需的值。',
    'current_password' => '密码不正确。',
    'date' => ':attribute 字段必须是有效的日期。',
    'date_equals' => ':attribute 字段必须与 :date 是相同的日期。',
    'date_format' => ':attribute 字段必须与 :format 格式一致。',
    'decimal' => ':attribute 字段必须是 :decimal 位小数。',
    'declined' => ':attribute 字段必须拒绝。',
    'declined_if' => '当 :other 为 :value 时，:attribute 字段必须拒绝。',
    'different' => ':attribute 字段与 :other 必须不同。',
    'digits' => ':attribute 字段必须是 :digits 位数字。',
    'digits_between' => ':attribute 字段必须在 :min ~ :max 位数字之间。',
    'dimensions' => ':attribute 字段的图片尺寸不正确。',
    'distinct' => ':attribute 字段存在重复的值。',
    'doesnt_end_with' => ':attribute 字段不能以下列内容结尾：:values。',
    'doesnt_start_with' => ':attribute 字段不能以下列内容开头：:values。',
    'email' => ':attribute 字段必须是有效的邮箱地址。',
    'ends_with' => ':attribute 字段必须以下列之一结尾：:values。',
    'enum' => '所选的 :attribute 不正确。',
    'exists' => '所选的 :attribute 不正确。',
    'extensions' => ':attribute 字段必须是以下扩展名之一：:values。',
    'file' => ':attribute 字段必须是文件。',
    'filled' => ':attribute 字段必须有值。',
    'gt' => [
        'array' => ':attribute 字段包含的项目必须多于 :value 个。',
        'file' => ':attribute 字段必须大于 :value KB。',
        'numeric' => ':attribute 字段必须大于 :value。',
        'string' => ':attribute 字段必须多于 :value 个字符。',
    ],
    'gte' => [
        'array' => ':attribute 字段必须包含 :value 个或更多项目。',
        'file' => ':attribute 字段必须大于或等于 :value KB。',
        'numeric' => ':attribute 字段必须大于或等于 :value。',
        'string' => ':attribute 字段必须多于或等于 :value 个字符。',
    ],
    'hex_color' => ':attribute 字段必须是有效的十六进制颜色值。',
    'image' => ':attribute 字段必须是图片。',
    'in' => '所选的 :attribute 不正确。',
    'in_array' => ':attribute 字段必须存在于 :other 中。',
    'integer' => ':attribute 字段必须是整数。',
    'ip' => ':attribute 字段必须是有效的 IP 地址。',
    'ipv4' => ':attribute 字段必须是有效的 IPv4 地址。',
    'ipv6' => ':attribute 字段必须是有效的 IPv6 地址。',
    'json' => ':attribute 字段必须是有效的 JSON 字符串。',
    'list' => ':attribute 字段必须是列表。',
    'lowercase' => ':attribute 字段必须为小写。',
    'lt' => [
        'array' => ':attribute 字段包含的项目必须少于 :value 个。',
        'file' => ':attribute 字段必须小于 :value KB。',
        'numeric' => ':attribute 字段必须小于 :value。',
        'string' => ':attribute 字段必须少于 :value 个字符。',
    ],
    'lte' => [
        'array' => ':attribute 字段不能超过 :value 个项目。',
        'file' => ':attribute 字段必须小于或等于 :value KB。',
        'numeric' => ':attribute 字段必须小于或等于 :value。',
        'string' => ':attribute 字段必须少于或等于 :value 个字符。',
    ],
    'mac_address' => ':attribute 字段必须是有效的 MAC 地址。',
    'max' => [
        'array' => ':attribute 字段不能超过 :max 个项目。',
        'file' => ':attribute 字段不能超过 :max KB。',
        'numeric' => ':attribute 字段不能超过 :max。',
        'string' => ':attribute 字段不能超过 :max 个字符。',
    ],
    'max_digits' => ':attribute 字段不能超过 :max 位数字。',
    'mimes' => ':attribute 字段必须是以下类型的文件：:values。',
    'mimetypes' => ':attribute 字段必须是以下类型的文件：:values。',
    'min' => [
        'array' => ':attribute 字段至少需要 :min 个项目。',
        'file' => ':attribute 字段至少需要 :min KB。',
        'numeric' => ':attribute 字段至少需要 :min。',
        'string' => ':attribute 字段至少需要 :min 个字符。',
    ],
    'min_digits' => ':attribute 字段至少需要 :min 位数字。',
    'missing' => ':attribute 字段必须不存在。',
    'missing_if' => '当 :other 为 :value 时，:attribute 字段必须不存在。',
    'missing_unless' => '当 :other 不为 :value 时，:attribute 字段必须不存在。',
    'missing_with' => '当存在 :values 时，:attribute 字段必须不存在。',
    'missing_with_all' => '当 :values 全部存在时，:attribute 字段必须不存在。',
    'multiple_of' => ':attribute 字段必须是 :value 的倍数。',
    'not_in' => '所选的 :attribute 不正确。',
    'not_regex' => ':attribute 字段格式不正确。',
    'numeric' => ':attribute 字段必须是数字。',
    'password' => [
        'letters' => ':attribute 字段必须至少包含一个字母。',
        'mixed' => ':attribute 字段必须至少包含一个大写字母和一个小写字母。',
        'numbers' => ':attribute 字段必须至少包含一个数字。',
        'symbols' => ':attribute 字段必须至少包含一个符号。',
        'uncompromised' => '所填写的 :attribute 曾出现在数据泄露中。请选择其他 :attribute。',
    ],
    'present' => ':attribute 字段必须存在。',
    'present_if' => '当 :other 为 :value 时，:attribute 字段必须存在。',
    'present_unless' => '当 :other 不为 :value 时，:attribute 字段必须存在。',
    'present_with' => '当存在 :values 时，:attribute 字段必须存在。',
    'present_with_all' => '当 :values 全部存在时，:attribute 字段必须存在。',
    'prohibited' => ':attribute 字段被禁止。',
    'prohibited_if' => '当 :other 为 :value 时，:attribute 字段被禁止。',
    'prohibited_unless' => '当 :other 不在 :values 中时，:attribute 字段被禁止。',
    'prohibits' => ':attribute 字段禁止 :other 存在。',
    'regex' => ':attribute 字段格式不正确。',
    'required' => ':attribute 字段为必填项。',
    'required_array_keys' => ':attribute 字段必须包含以下项目：:values。',
    'required_if' => '当 :other 为 :value 时，:attribute 字段为必填项。',
    'required_if_accepted' => '当 :other 被接受时，:attribute 字段为必填项。',
    'required_if_declined' => '当 :other 被拒绝时，:attribute 字段为必填项。',
    'required_unless' => '当 :other 不在 :values 中时，:attribute 字段为必填项。',
    'required_with' => '当存在 :values 时，:attribute 字段为必填项。',
    'required_with_all' => '当 :values 全部存在时，:attribute 字段为必填项。',
    'required_without' => '当 :values 不存在时，:attribute 字段为必填项。',
    'required_without_all' => '当 :values 全部不存在时，:attribute 字段为必填项。',
    'same' => ':attribute 字段与 :other 必须一致。',
    'size' => [
        'array' => ':attribute 字段必须包含 :size 个项目。',
        'file' => ':attribute 字段必须为 :size KB。',
        'numeric' => ':attribute 字段必须为 :size。',
        'string' => ':attribute 字段必须为 :size 个字符。',
    ],
    'starts_with' => ':attribute 字段必须以下列之一开头：:values。',
    'string' => ':attribute 字段必须是字符串。',
    'timezone' => ':attribute 字段必须是有效的时区。',
    'unique' => ':attribute 已被使用。',
    'uploaded' => ':attribute 上传失败。',
    'uppercase' => ':attribute 字段必须为大写。',
    'url' => ':attribute 字段必须是有效的 URL。',
    'ulid' => ':attribute 字段必须是有效的 ULID。',
    'uuid' => ':attribute 字段必须是有效的 UUID。',
    'custom_translation' => [
        'layout_name' => [
            'required' => '布局名称为必填项。',
            'string' => '布局名称必须为字符串。',
            'max' => '布局名称不能超过 :max 个字符。',
        ],
        'locale' => [
            'required' => '区域设置为必填项。',
            'string' => '区域设置必须为字符串。',
        ],
        'value' => [
            'required' => '翻译值为必填项。',
            'string' => '翻译值必须为字符串。',
        ],
        'values' => [
            'required' => '翻译值为必填项。',
            'array' => '翻译值必须是按区域设置分组的对象。',
        ],
        'status' => [
            'in' => '状态必须为 active 或 orphaned。',
        ],
        'expected_lock_version' => [
            'required' => '保存请求中缺少 expected_lock_version。',
            'integer' => 'expected_lock_version 必须为整数。',
            'min' => 'expected_lock_version 必须大于或等于 0。',
        ],
        'ids' => [
            'required' => '请至少选择一个要删除的多语言键。',
            'array' => '删除对象必须是 ID 数组。',
            'min' => '请至少选择一个要删除的多语言键。',
            'integer' => '多语言键 ID 必须为整数。',
            'exists' => '包含不存在的多语言键。',
        ],
    ],
    'layout' => [
        'expected_lock_version' => [
            'required' => '保存请求中缺少 expected_lock_version。',
            'integer' => 'expected_lock_version 必须为整数。',
            'min' => 'expected_lock_version 必须大于或等于 0。',
        ],
        'invalid_json' => 'JSON 格式无效。',
        'must_be_array' => '布局数据必须是数组。',
        'dangerous_expression' => '包含不被允许的表达式：:snippet',
        'external_resource_url' => '不允许使用外部资源 URL（仅允许同源路径）：:url',
        'required_field_missing' => "缺少必填字段 ':field'。",
        'version_must_be_string' => 'version 字段必须为字符串。',
        'layout_name_must_be_string' => 'layout_name 字段必须为字符串。',
        'components_must_be_array' => 'components 字段必须为数组。',
        'components_or_slots_required' => '继承布局需要 components 或 slots 其中之一。',
        'component_must_be_array' => 'components[:index] 必须为数组。',
        'max_depth_exceeded' => '组件嵌套深度超过了最大允许深度（:max）。',
        'component_required_field_missing' => "components[:index] 中缺少必填字段 ':field'。",
        'component_field_must_be_string' => 'components[:index].component 必须为字符串。',
        'component_name_must_be_string' => 'components[:index].name 必须为字符串。',
        'component_type_invalid' => 'components[:index].type 必须为 basic、composite、layout 之一。',
        'props_must_be_object' => 'components[:index].props 必须为对象（数组）。',
        'children_must_be_array' => 'components[:index].children 必须为数组。',
        'permissions_must_be_array' => 'components[:index].permissions 必须为数组。',
        'permissions_must_be_array_or_object' => 'permissions 必须为数组或结构化对象（or/and）。',
        'permissions_invalid_operator' => 'permissions 结构中有效的运算符仅允许 "or" 或 "and"。键必须恰好为 1 个。',
        'permissions_operator_must_be_array' => 'permissions 的 ":operator" 运算符值必须为数组。',
        'permissions_operator_min_items' => 'permissions 的 ":operator" 运算符至少需要 :min 个项目。',
        'permissions_max_depth_exceeded' => '超过了 permissions 结构的最大嵌套深度（:max）。',
        'permission_must_be_string' => 'components[:index].permissions[:perm_index] 必须为字符串。',
        'permission_must_be_string_or_group' => 'permissions 的项目[:index] 必须为字符串（权限标识符）或结构化对象（or/and）。',
        'permission_invalid_format' => 'components[:index].permissions 中的 ":permission" 不是正确的权限标识符格式。',
        'actions_must_be_array' => 'components[:index].actions 必须为数组。',
        'action_must_be_array' => 'components[:index].actions[:actionIndex] 必须为数组。',
        'action_type_missing' => "components[:index].actions[:actionIndex] 中缺少必填字段 'type'。",
        'action_type_or_event_missing' => "components[:index].actions[:actionIndex] 需要 'type' 或 'event' 其中之一。",
        'action_type_must_be_string' => 'components[:index].actions[:actionIndex].type 必须为字符串。',
        'action_event_must_be_string' => 'components[:index].actions[:actionIndex].event 必须为字符串。',
        'content' => [
            'required' => '需要布局 content。',
            'array' => '布局 content 必须为数组。',
        ],
        'version' => [
            'required' => '需要布局版本。',
            'string' => '布局版本必须为字符串。',
        ],
        'layout_name' => [
            'required' => '需要布局名称。',
            'string' => '布局名称必须为字符串。',
            'max' => '布局名称不能超过 :max 个字符。',
        ],
        'endpoint' => [
            'required' => '需要 API 端点。',
            'string' => 'API 端点必须为字符串。',
        ],
        'extends' => [
            'string' => 'extends 必须为字符串。',
        ],
        'slots' => [
            'array' => 'slots 必须为数组。',
        ],
        'components' => [
            'required' => '需要组件数组。',
            'array' => 'components 字段必须为数组。',
        ],
        'data_sources' => [
            'array' => 'data_sources 字段必须为数组。',
        ],
        'metadata' => [
            'array' => 'metadata 字段必须为数组。',
        ],
        'meta' => [
            'array' => 'meta 字段必须为数组。',
            'title' => [
                'string' => 'meta.title 必须为字符串。',
            ],
            'description' => [
                'string' => 'meta.description 必须为字符串。',
            ],
            'keywords' => [
                'string' => 'meta.keywords 必须为字符串。',
            ],
            'auth_required' => [
                'boolean' => 'meta.auth_required 必须为布尔值。',
            ],
            'is_base' => [
                'boolean' => 'meta.is_base 必须为布尔值。',
            ],
            'guest_only' => [
                'boolean' => 'meta.guest_only 必须为布尔值。',
            ],
            'is_error_layout' => [
                'boolean' => 'meta.is_error_layout 必须为布尔值。',
            ],
            'error_code' => [
                'integer' => 'meta.error_code 必须为整数。',
            ],
            'seo' => [
                'array' => 'meta.seo 必须为数组。',
                'enabled' => [
                    'boolean' => 'meta.seo.enabled 必须为布尔值。',
                ],
                'data_sources' => [
                    'array' => 'meta.seo.data_sources 必须为数组。',
                    'string' => 'meta.seo.data_sources 的每个项目必须为字符串。',
                ],
                'priority' => [
                    'numeric' => 'meta.seo.priority 必须为数字。',
                    'min' => 'meta.seo.priority 必须大于或等于 0。',
                    'max' => 'meta.seo.priority 必须小于或等于 1。',
                ],
                'changefreq' => [
                    'string' => 'meta.seo.changefreq 必须为字符串。',
                    'in' => 'meta.seo.changefreq 必须为 always、hourly、daily、weekly、monthly、yearly、never 之一。',
                ],
                'og' => [
                    'array' => 'meta.seo.og 必须为数组。',
                ],
                'structured_data' => [
                    'array' => 'meta.seo.structured_data 必须为数组。',
                ],
                'page_type' => [
                    'string' => 'meta.seo.page_type 必须为字符串。',
                ],
                'toggle_setting' => [
                    'string' => 'meta.seo.toggle_setting 必须为字符串。',
                ],
                'vars' => [
                    'array' => 'meta.seo.vars 必须为数组。',
                ],
                'extensions' => [
                    'array' => 'meta.seo.extensions 必须为数组。',
                ],
            ],
        ],
        'modals' => [
            'array' => 'modals 字段必须为数组。',
        ],
        'state' => [
            'array' => 'state 字段必须为数组。',
        ],
        'init_actions' => [
            'array' => 'init_actions 字段必须为数组。',
        ],
        'defines' => [
            'array' => 'defines 字段必须为数组。',
        ],
        'init_state' => [
            'array' => 'init_state 字段必须为数组。',
        ],
        'initLocal' => [
            'array' => 'initLocal 字段必须为数组。',
        ],
        'initGlobal' => [
            'array' => 'initGlobal 字段必须为数组。',
        ],
        'global_state' => [
            'array' => 'global_state 字段必须为数组。',
        ],
        'errorHandling' => [
            'array' => 'errorHandling 字段必须为数组。',
        ],
        'actions' => [
            'array' => 'actions 字段必须为数组。',
        ],
        'pageConfig' => [
            'array' => 'pageConfig 字段必须为数组。',
        ],
        'schema' => [
            'array' => 'schema 字段必须为数组。',
        ],
        'routes' => [
            'array' => 'routes 字段必须为数组。',
        ],
        'computed' => [
            'array' => 'computed 字段必须为数组。',
        ],
        'permissions' => [
            'array' => 'permissions 字段必须为数组。',
            'string' => '每个权限标识符必须为字符串。',
            'regex' => '权限标识符格式不正确。（例：module.entity.action）',
        ],
        'globalHeaders' => [
            'array' => 'globalHeaders 字段必须为数组。',
            'pattern' => [
                'required' => '每条 globalHeaders 规则都需要 pattern 字段。',
                'string' => 'globalHeaders pattern 必须为字符串。',
            ],
            'headers' => [
                'required' => '每条 globalHeaders 规则都需要 headers 字段。',
                'array' => 'globalHeaders headers 必须为数组。',
                'string' => '标头值必须为字符串。',
            ],
        ],
        'transition_overlay' => [
            'enabled' => [
                'boolean' => '过渡遮罩的启用值必须为 true 或 false。',
            ],
            'style' => [
                'string' => '过渡遮罩样式必须为字符串。',
                'in' => '过渡遮罩样式必须为 opaque、blur、fade、skeleton 之一。',
            ],
            'target' => [
                'string' => '过渡遮罩目标必须为字符串。',
                'max' => '过渡遮罩目标不能超过 :max 个字符。',
            ],
            'fallback_target' => [
                'string' => '过渡遮罩备用目标必须为字符串。',
                'max' => '过渡遮罩备用目标不能超过 :max 个字符。',
            ],
            'skeleton' => [
                'array' => '骨架屏设置必须为数组。',
                'component' => [
                    'string' => '骨架屏组件名称必须为字符串。',
                    'max' => '骨架屏组件名称不能超过 :max 个字符。',
                ],
                'animation' => [
                    'string' => '骨架屏动画必须为字符串。',
                    'in' => '骨架屏动画必须为 pulse、wave、none 之一。',
                ],
                'iteration_count' => [
                    'integer' => '骨架屏重复次数必须为整数。',
                    'min' => '骨架屏重复次数至少为 :min。',
                    'max' => '骨架屏重复次数不能超过 :max。',
                ],
            ],
            'wait_for' => [
                'background' => 'wait_for 中不能指定 background 数据源（无法阻塞用户）：:id',
                'websocket' => 'wait_for 中不能指定 websocket 数据源（没有 fetch 完成事件）：:id',
            ],
        ],
    ],
    'layout_extension' => [
        'expected_lock_version' => [
            'required' => '保存请求中缺少 expected_lock_version。',
            'integer' => 'expected_lock_version 必须为整数。',
            'min' => 'expected_lock_version 必须大于或等于 0。',
        ],
        'invalid_json' => 'JSON 格式无效。',
        'must_be_array' => '布局扩展数据必须是数组。',
        'target_required' => "扩展定义需要 'extension_point' 或 'target_layout' 其中之一。",
        'target_exclusive' => "'extension_point' 与 'target_layout' 不能同时指定。",
        'extension_point_invalid' => 'extension_point 字段必须是非空字符串。',
        'target_layout_invalid' => 'target_layout 字段必须是非空字符串。',
        'components_must_be_array' => 'components 字段必须为数组。',
        'injections_required' => 'overlay 扩展需要 injections 字段。',
        'injections_must_be_array' => 'injections 字段必须为数组。',
        'injection_must_be_array' => 'injections[:index] 必须为数组。',
        'injection_target_id_required' => 'injections[:index] 需要 target_id 字段。',
        'injection_position_invalid' => 'injections[:index].position 的值无效。',
        'injection_components_must_be_array' => 'injections[:index].components 必须为数组。',
        'injection_props_must_be_array' => 'injections[:index].props 必须为数组。',
        'section_must_be_array' => ':section 字段必须为数组。',
        'max_depth_exceeded' => '组件嵌套深度超过了最大允许深度（:max）。',
        'component_must_be_array' => 'components[:index] 必须为数组。',
        'component_required_field_missing' => "components[:index] 中缺少必填字段 ':field'。",
        'component_name_must_be_string' => 'components[:index].name 必须为字符串。',
        'component_type_invalid' => 'components[:index].type 必须为 basic、composite、layout 之一。',
        'props_must_be_object' => 'components[:index].props 必须为对象（数组）。',
        'children_must_be_array' => 'components[:index].children 必须为数组。',
        'content' => [
            'required' => '扩展内容为必填项。',
            'array' => '扩展内容必须为数组。',
        ],
        'priority' => [
            'integer' => 'priority 必须为整数。',
            'min' => 'priority 必须大于或等于 0。',
            'max' => 'priority 必须小于或等于 9999。',
        ],
        'data_sources' => [
            'array' => 'data_sources 必须为数组。',
        ],
        'preview_layout' => [
            'string' => '预览布局名称必须为字符串。',
            'max' => '预览布局名称不能超过 255 个字符。',
            'required' => '扩展点预览需要选择代表布局。',
        ],
    ],
    'endpoint' => [
        'must_be_string' => 'API 端点必须为字符串。',
        'external_url_not_allowed' => '不允许使用外部 URL。',
        'not_whitelisted' => '不被允许的 API 端点。允许的模式：:pattern',
        'path_traversal_detected' => '检测到路径遍历攻击。',
    ],
    'external_url' => [
        'detected_in_props' => '在 props 中检测到外部 URL：:url',
        'detected_in_actions' => '在 actions 中检测到外部 URL：:url',
        'http_not_allowed' => '不允许使用 HTTP 协议的 URL。',
        'https_not_allowed' => '不允许使用 HTTPS 协议的 URL。',
        'data_uri_not_allowed' => '不允许使用 Data URI 方案。',
        'javascript_uri_not_allowed' => '不允许使用 JavaScript URI 方案。',
        'dangerous_scheme_detected' => '检测到危险的 URI 方案：:scheme',
    ],
    'outbound_url' => [
        'invalid' => 'URL 格式不正确。请输入以 http 或 https 开头的地址。',
        'internal_not_allowed' => '不能使用内网地址（私有 IP、localhost 等）。请输入可从外部访问的地址。',
    ],
    'schedule_command' => [
        'shell_not_allowed' => '不允许的 Shell 命令。只能使用服务器上已登记的可执行文件，且不能使用管道（|）、分号（;）等特殊字符。',
        'shell_interpreter_denied' => '不能通过解释器执行内联命令／代码或指定不安全的路径。解释器后只能指定绝对路径的脚本文件。',
        'artisan_denied' => '出于安全考虑，此 Artisan 命令不能作为计划任务运行。',
        'artisan_not_allowlisted' => '该 Artisan 命令不在允许定时执行的名单内。只能登记清理缓存、处理队列等维护类命令。',
        'artisan_malformed' => 'Artisan 命令格式不正确。不能使用引号、反斜杠和短选项（-v），只能登记 "命令名 --选项[=值]" 形式。',
        'artisan_option_denied' => '此 Artisan 命令包含不被允许的选项。',
        'artisan_argument_denied' => '此 Artisan 命令不能附加额外参数。',
    ],
    'component' => [
        'template_id_required' => '校验组件需要 template_id。',
        'manifest_not_found' => '找不到模板 :templateId 的组件清单文件（components.json）。',
        'name_empty' => 'components[:index].component 名称不能为空。',
        'not_found' => "组件 ':component' 未在模板中注册。(components[:index])",
    ],
    'request' => [
        'template_id' => [
            'required' => '模板 ID 为必填项。',
            'integer' => '模板 ID 必须为整数。',
            'exists' => '该模板不存在。',
        ],
        'layout_name' => [
            'required' => '布局名称为必填项。',
            'string' => '布局名称必须为字符串。',
            'max' => '布局名称不能超过 :max 个字符。',
            'unique' => '该布局名称已存在。',
        ],
        'content' => [
            'required' => '布局内容为必填项。',
            'array' => '布局内容必须为数组（对象）。',
        ],
    ],
    'layout_inheritance' => [
        'parent_not_found' => '找不到父级布局 ":parent"。',
        'parent_not_in_same_template' => '父级布局必须位于同一模板内。',
        'circular_reference' => '检测到布局循环引用：:trace',
        'max_depth_exceeded' => '布局继承深度超过了最大允许深度（:max）。',
        'extends_must_be_string' => 'extends 字段必须为字符串。',
        'slots_must_be_object' => 'slots 字段必须为对象。',
        'slot_name_must_be_string' => '插槽名称必须为字符串。',
        'slot_value_must_be_array' => 'slots[:slotName] 必须为数组。',
        'slot_not_defined_in_parent' => '插槽 ":slotName" 未在父级布局中定义。',
        'parent_has_no_slots' => '父级布局中没有定义插槽。',
        'data_source_id_duplicate' => 'data_sources 中存在重复的 ID ":id"。',
        'data_sources_must_be_array' => 'data_sources 必须为数组。',
        'data_source_must_have_id' => 'data_sources[:index] 中缺少必填字段 "id"。',
        'data_source_id_must_be_string' => 'data_sources[:index].id 必须为字符串。',
    ],
    'notification_channel' => [
        'invalid' => '通知渠道标识符不正确。',
        'unavailable' => "不可用的通知渠道：':value'",
    ],
    'translatable' => [
        'must_be_array' => '多语言字段必须为数组。',
        'unsupported_language' => "不支持的语言代码：':lang'",
        'must_be_string' => "':lang' 翻译必须为字符串。",
        'max_length' => "':lang' 翻译不能超过 :max 个字符。",
        'min_length' => "':lang' 翻译至少需要 :min 个字符。",
        'at_least_one_required' => '至少需要一种语言的翻译。',
        'current_locale_required' => ':locale 语言的值为必填项。',
    ],
    'menu' => [
        'roles' => [
            'array' => '角色列表必须为数组。',
            'integer' => '角色 ID 必须为数字。',
            'exists' => '找不到所选的角色。',
        ],
        'name' => [
            'required' => '请输入菜单名称。',
        ],
        'slug' => [
            'required' => '请输入别名。',
            'unique' => '该别名已被使用。',
            'max' => '别名不能超过 :max 个字符。',
        ],
        'url' => [
            'required' => '请输入路径（URL）。',
            'max' => 'URL 不能超过 :max 个字符。',
        ],
        'icon' => [
            'max' => '图标不能超过 :max 个字符。',
        ],
        'order' => [
            'integer' => '排序必须为整数。',
            'min' => '排序必须大于或等于 :min。',
        ],
        'parent_id' => [
            'exists' => '上级菜单不存在。',
        ],
        'is_active' => [
            'boolean' => '启用状态必须为 true 或 false。',
        ],
        'extension_type' => [
            'in' => '扩展类型必须为 core、module、plugin 之一。',
        ],
        'extension_identifier' => [
            'max' => '扩展标识符最多可输入 255 个字符。',
            'must_be_string' => '扩展标识符必须为字符串。',
            'min_parts' => '扩展标识符必须为 vendor-name 格式（例：sirsoft-board）。',
            'empty_part' => '扩展标识符中存在空的部分。连字符不能连续出现，也不能位于两端。',
            'invalid_characters' => '扩展标识符只能使用小写英文字母、数字和下划线（_）。',
            'empty_word' => '扩展标识符中下划线不能连续出现，也不能位于两端。',
            'word_starts_with_digit' => '扩展标识符的每个单词不能以数字开头。',
        ],
        'parent_menus' => [
            'required' => '上级菜单排序数组为必填项。',
            'array' => '上级菜单排序必须为数组。',
            'min' => '至少需要 1 个上级菜单。',
            'id' => [
                'required' => '每个上级菜单 ID 均为必填项。',
                'integer' => '上级菜单 ID 必须为整数。',
                'exists' => '包含不存在的上级菜单 ID。',
            ],
            'order' => [
                'required' => '每个上级菜单排序均为必填项。',
                'integer' => '上级菜单排序必须为整数。',
                'min' => '菜单排序必须大于或等于 1。',
            ],
        ],
        'child_menus' => [
            'array' => '下级菜单排序必须为数组。',
            'id' => [
                'required' => '每个下级菜单 ID 均为必填项。',
                'integer' => '下级菜单 ID 必须为整数。',
                'exists' => '包含不存在的下级菜单 ID。',
            ],
            'order' => [
                'required' => '每个下级菜单排序均为必填项。',
                'integer' => '下级菜单排序必须为整数。',
                'min' => '菜单排序必须大于或等于 1。',
            ],
        ],
        'moved_items' => [
            'array' => '移动项目必须为数组。',
            'id' => [
                'required' => '要移动的菜单 ID 为必填项。',
                'integer' => '菜单 ID 必须为整数。',
                'exists' => '包含不存在的菜单 ID。',
            ],
            'new_parent_id' => [
                'integer' => '新的上级菜单 ID 必须为整数。',
                'exists' => '该上级菜单 ID 不存在。',
            ],
        ],
    ],
    'permission' => [
        'name' => [
            'required' => '请输入权限名称。',
        ],
        'description' => [
            'max' => '权限说明不能超过 :max 个字符。',
        ],
    ],
    'role' => [
        'name' => [
            'required' => '请输入角色名称。',
        ],
        'description' => [
            'max' => '角色说明不能超过 :max 个字符。',
        ],
    ],
    'template' => [
        'name' => [
            'max' => '模板名称不能超过 :max 个字符。',
        ],
        'description' => [
            'max' => '模板说明不能超过 :max 个字符。',
        ],
        'metadata' => [
            'array' => 'metadata 必须为数组。',
        ],
        'status' => [
            'in' => 'status 必须为 active 或 inactive。',
        ],
    ],
    'module' => [
        'status' => [
            'in' => 'status 必须为 active、inactive、installed、uninstalled 之一。',
        ],
    ],
    'plugin' => [
        'status' => [
            'in' => 'status 必须为 active、inactive、installed、uninstalled 之一。',
        ],
    ],
    'template_path' => [
        'must_be_string' => '模板路径必须为字符串。',
        'traversal_detected' => '检测到路径遍历模式：:pattern',
        'absolute_path_not_allowed' => '不允许使用绝对路径。',
        'null_byte_detected' => '检测到 NULL 字节攻击。',
        'outside_base_directory' => '不允许使用基准目录之外的路径。',
        'file_type_not_allowed' => '不允许的文件类型。扩展名：:extension（允许：:allowed）',
    ],
    'extension_identifier' => [
        'max' => '扩展标识符最多可输入 255 个字符。',
        'must_be_string' => '扩展标识符必须为字符串。',
        'min_parts' => '扩展标识符必须为 vendor-name 格式（例：sirsoft-board）。',
        'empty_part' => '扩展标识符中存在空的部分。连字符不能连续出现，也不能位于两端。',
        'invalid_characters' => '扩展标识符只能使用小写英文字母、数字和下划线（_）。',
        'empty_word' => '扩展标识符中下划线不能连续出现，也不能位于两端。',
        'word_starts_with_digit' => '扩展标识符的每个单词不能以数字开头。',
    ],
    'module_path' => [
        'file_type_not_allowed' => '不允许的文件类型。扩展名：:extension（允许：:allowed）',
        'must_be_string' => '路径必须为字符串。',
        'traversal_detected' => '检测到路径遍历：:pattern',
        'absolute_path_not_allowed' => '不允许使用绝对路径。',
        'null_byte_detected' => '检测到 NULL 字节。',
        'outside_base_directory' => '不允许访问基准目录之外的位置。',
    ],
    'plugin_path' => [
        'file_type_not_allowed' => '不允许的文件类型。扩展名：:extension（允许：:allowed）',
        'must_be_string' => '路径必须为字符串。',
        'traversal_detected' => '检测到路径遍历：:pattern',
        'absolute_path_not_allowed' => '不允许使用绝对路径。',
        'null_byte_detected' => '检测到 NULL 字节。',
        'outside_base_directory' => '不允许访问基准目录之外的位置。',
    ],
    'auth' => [
        'two_factor' => [
            'challenge_required' => '没有认证请求信息。请重新登录。',
            'challenge_invalid' => '认证请求信息不正确。',
            'code_required' => '请输入验证码。',
        ],
        'email' => [
            'required' => '邮箱为必填项。',
            'email' => '邮箱格式不正确。',
            'exists' => '该邮箱尚未注册。',
            'unique' => '该邮箱已被使用。',
        ],
        'password' => [
            'required' => '密码为必填项。',
            'min' => '密码至少需要 :min 个字符。',
            'confirmed' => '两次输入的密码不一致。',
        ],
        'name' => [
            'required' => '姓名为必填项。',
            'min' => '姓名至少需要 :min 个字符。',
            'max' => '姓名不能超过 :max 个字符。',
        ],
        'nickname' => [
            'max' => '昵称不能超过 :max 个字符。',
        ],
        'mobile' => [
            'max' => '手机号码不能超过 :max 个字符。',
            'regex' => '手机号码只能输入数字和 -、+、()、空格。',
        ],
        'phone' => [
            'max' => '电话号码不能超过 :max 个字符。',
            'regex' => '电话号码只能输入数字和 -、+、()、空格。',
        ],
        'agree_terms' => [
            'accepted' => '请同意服务条款。',
        ],
        'agree_privacy' => [
            'accepted' => '请同意隐私政策。',
        ],
        'token' => [
            'required' => '令牌为必填项。',
            'string' => '令牌必须为字符串。',
        ],
    ],
    'asset' => [
        'identifier' => [
            'required' => '标识符为必填项。',
            'string' => '标识符必须为字符串。',
        ],
        'path' => [
            'required' => '路径为必填项。',
            'string' => '路径必须为字符串。',
        ],
    ],
    'setting' => [
        'value' => [
            'present' => '请求中必须包含设置值项（value）。',
            'boolean' => '该设置只能保存启用／停用值。',
            'integer' => '该设置只能保存整数。',
            'numeric' => '该设置只能保存数字。',
            'type' => '该设置值的格式无法保存。',
            'max' => '设置值不能超过 :max 个字符。',
            'array_max' => '设置值的大小不能超过 :max 个字符。',
        ],
    ],
    'exclude_current_user' => '当前登录的用户不能包含在批量变更对象中。',
    'not_self_parent' => '不能将自身设置为上级。',
    'not_circular_parent' => '不能移动到自身的下级菜单中。',
    'settings' => [
        'site_name_required' => '请输入站点名称。',
        'site_name_max' => '站点名称不能超过 100 个字符。',
        'site_url_required' => '请输入站点 URL。',
        'site_url_invalid' => 'URL 格式不正确。',
        'site_url_max' => '站点 URL 不能超过 255 个字符。',
        'site_description_max' => '站点说明不能超过 500 个字符。',
        'admin_email_required' => '请输入管理员邮箱。',
        'admin_email_invalid' => '邮箱格式不正确。',
        'admin_email_max' => '管理员邮箱不能超过 255 个字符。',
        'timezone_required' => '请选择时区。',
        'timezone_invalid' => '请选择正确的时区。',
        'language_required' => '请选择默认语言。',
        'language_invalid' => '请选择正确的语言。',
        'currency_max' => '货币代码不能超过 10 个字符。',
        'maintenance_mode_boolean' => '维护模式必须为 true 或 false。',
        'mailer_required' => '请选择邮件驱动。',
        'mailer_invalid' => '请选择正确的邮件驱动。',
        'host_required' => '请输入 SMTP 主机。',
        'host_max' => 'SMTP 主机不能超过 255 个字符。',
        'port_required' => '请输入端口。',
        'port_integer' => '端口必须为整数。',
        'port_min' => '端口必须大于或等于 1。',
        'port_max' => '端口不能超过 65535。',
        'username_max' => '用户名不能超过 255 个字符。',
        'password_max' => '密码不能超过 255 个字符。',
        'encryption_invalid' => '请选择正确的加密方式。',
        'from_address_required' => '请输入发件人邮箱。',
        'from_address_invalid' => '邮箱格式不正确。',
        'from_address_max' => '发件人邮箱不能超过 255 个字符。',
        'from_name_required' => '请输入发件人名称。',
        'from_name_max' => '发件人名称不能超过 255 个字符。',
        'max_file_size_required' => '请输入最大文件大小。',
        'max_file_size_integer' => '最大文件大小必须为整数。',
        'max_file_size_min' => '最大文件大小必须大于或等于 1MB。',
        'max_file_size_max' => '最大文件大小不能超过 1024MB。',
        'allowed_extensions_required' => '请输入允许的扩展名。',
        'allowed_extensions_max' => '允许的扩展名不能超过 500 个字符。',
        'allowed_extensions_invalid_type' => '允许的扩展名必须为字符串或数组。',
        'image_max_width_integer' => '图片最大宽度必须为整数。',
        'image_max_width_min' => '图片最大宽度必须大于或等于 100px。',
        'image_max_width_max' => '图片最大宽度不能超过 10000px。',
        'image_max_height_integer' => '图片最大高度必须为整数。',
        'image_max_height_min' => '图片最大高度必须大于或等于 100px。',
        'image_max_height_max' => '图片最大高度不能超过 10000px。',
        'image_quality_integer' => '图片质量必须为整数。',
        'image_quality_min' => '图片质量必须大于或等于 1。',
        'image_quality_max' => '图片质量不能超过 100。',
        'orphan_cleanup_enabled_boolean' => '孤立附件自动清理必须为启用或停用之一。',
        'orphan_retention_days_integer' => '孤立附件保留期限必须为整数。',
        'orphan_retention_days_min' => '孤立附件保留期限必须大于或等于 1 天。',
        'orphan_retention_days_max' => '孤立附件保留期限不能超过 3650 天。',
        'meta_title_suffix_max' => '标题后缀不能超过 100 个字符。',
        'meta_description_max' => 'Meta 说明不能超过 160 个字符。',
        'meta_keywords_max' => 'Meta 关键词不能超过 255 个字符。',
        'google_analytics_id_max' => 'Google Analytics ID 不能超过 50 个字符。',
        'google_site_verification_max' => 'Google 站点验证码不能超过 100 个字符。',
        'naver_site_verification_max' => 'Naver 站点验证码不能超过 100 个字符。',
        'generator_enabled_boolean' => 'Generator 标签显示设置必须为 true 或 false。',
        'generator_content_string' => 'Generator 内容必须为字符串。',
        'generator_content_max' => 'Generator 内容不能超过 200 个字符。',
        'bot_user_agents_array' => '爬虫 User-Agent 列表必须为数组。',
        'bot_user_agents_item_string' => '爬虫 User-Agent 项目必须为字符串。',
        'bot_user_agents_item_max' => '爬虫 User-Agent 项目不能超过 100 个字符。',
        'bot_detection_enabled_boolean' => '爬虫检测设置必须为 true 或 false。',
        'bot_detection_library_enabled_boolean' => '爬虫检测库设置必须为 true 或 false。',
        'og_default_site_name_string' => 'OG 站点名称默认值必须为字符串。',
        'og_default_site_name_max' => 'OG 站点名称默认值不能超过 200 个字符。',
        'og_image_default_width_integer' => 'OG 图片默认宽度必须为整数。',
        'og_image_default_width_min' => 'OG 图片默认宽度必须大于或等于 0。',
        'og_image_default_width_max' => 'OG 图片默认宽度必须小于或等于 8000。',
        'og_image_default_height_integer' => 'OG 图片默认高度必须为整数。',
        'og_image_default_height_min' => 'OG 图片默认高度必须大于或等于 0。',
        'og_image_default_height_max' => 'OG 图片默认高度必须小于或等于 8000。',
        'twitter_default_card_string' => 'Twitter 卡片默认值必须为字符串。',
        'twitter_default_card_in' => 'Twitter 卡片默认值必须为 summary、summary_large_image、app、player 之一。',
        'twitter_default_site_string' => 'Twitter 站点账号必须为字符串。',
        'twitter_default_site_max' => 'Twitter 站点账号不能超过 50 个字符。',
        'seo_cache_enabled_boolean' => 'SEO 缓存设置必须为 true 或 false。',
        'seo_cache_ttl_integer' => 'SEO 缓存 TTL 必须为整数。',
        'seo_cache_ttl_min' => 'SEO 缓存 TTL 至少为 60 秒。',
        'seo_cache_ttl_max' => 'SEO 缓存 TTL 最多不能超过 86400 秒（24 小时）。',
        'sitemap_enabled_boolean' => 'Sitemap 生成设置必须为 true 或 false。',
        'sitemap_cache_ttl_integer' => 'Sitemap 缓存 TTL 必须为整数。',
        'sitemap_cache_ttl_min' => 'Sitemap 缓存 TTL 至少为 3600 秒（1 小时）。',
        'sitemap_cache_ttl_max' => 'Sitemap 缓存 TTL 最多不能超过 604800 秒（7 天）。',
        'sitemap_urls_per_file_integer' => 'Sitemap 每个文件的 URL 数必须为整数。',
        'sitemap_urls_per_file_min' => 'Sitemap 每个文件的 URL 数至少为 1000 个。',
        'sitemap_urls_per_file_max' => 'Sitemap 每个文件的 URL 数最多不能超过 50000 个。',
        'sitemap_gzip_boolean' => 'Sitemap 压缩设置必须为 true 或 false。',
        'sitemap_serve_stale_on_miss_boolean' => '提供旧版 Sitemap 的设置必须为 true 或 false。',
        'sitemap_max_urls_per_contributor_integer' => '每个收集器的最大 URL 数必须为整数。',
        'sitemap_max_urls_per_contributor_min' => '每个收集器的最大 URL 数必须大于或等于 0。',
        'sitemap_hreflang_enabled_boolean' => 'Sitemap 多语言替代链接（hreflang）设置必须为 true 或 false。',
        'sitemap_schedule_invalid' => '请选择有效的 Sitemap 生成周期。',
        'sitemap_schedule_time_invalid' => 'Sitemap 生成时刻必须为 HH:mm 格式。',
        'force_https_required' => '请选择强制 HTTPS 设置。',
        'force_https_boolean' => '强制 HTTPS 必须为 true 或 false。',
        'allow_internal_outbound_urls_boolean' => '允许调用内网地址必须为 true 或 false。',
        'login_attempt_enabled_required' => '请选择登录尝试限制设置。',
        'login_attempt_enabled_boolean' => '登录尝试限制必须为 true 或 false。',
        'auth_token_lifetime_integer' => '认证令牌有效时长必须为整数。',
        'auth_token_lifetime_min' => '认证令牌有效时长必须大于或等于 0。',
        'auth_token_lifetime_max' => '认证令牌有效时长最多不能超过 3600 分钟（60 小时）。',
        'auth_token_lifetime_range' => '认证令牌有效时长必须为 0（无限制）或介于 30~3600 分钟之间。',
        'max_login_attempts_integer' => '最大登录尝试次数必须为整数。',
        'max_login_attempts_min' => '最大登录尝试次数必须大于或等于 0。',
        'max_login_attempts_max' => '最大登录尝试次数不能超过 100 次。',
        'login_lockout_time_integer' => '封禁时长必须为整数。',
        'login_lockout_time_min' => '封禁时长必须大于或等于 0。',
        'login_lockout_time_max' => '封禁时长最多不能超过 1440 分钟（24 小时）。',
        'cache_enabled_required' => '请选择全局缓存启用设置。',
        'cache_enabled_boolean' => '缓存启用必须为 true 或 false。',
        'layout_cache_enabled_required' => '请选择布局缓存设置。',
        'layout_cache_enabled_boolean' => '布局缓存必须为 true 或 false。',
        'layout_cache_ttl_required' => '请输入布局缓存过期时间。',
        'layout_cache_ttl_integer' => '布局缓存过期时间必须为整数。',
        'layout_cache_ttl_min' => '布局缓存过期时间至少为 0 秒。',
        'layout_cache_ttl_max' => '布局缓存过期时间最多不能超过 14400 秒（4 小时）。',
        'stats_cache_enabled_required' => '请选择统计缓存设置。',
        'stats_cache_enabled_boolean' => '统计缓存必须为 true 或 false。',
        'stats_cache_ttl_required' => '请输入统计缓存过期时间。',
        'stats_cache_ttl_integer' => '统计缓存过期时间必须为整数。',
        'stats_cache_ttl_min' => '统计缓存过期时间至少为 0 秒。',
        'stats_cache_ttl_max' => '统计缓存过期时间最多不能超过 14400 秒（4 小时）。',
        'advanced_seo_cache_enabled_required' => '请选择 SEO 缓存设置。',
        'advanced_seo_cache_enabled_boolean' => 'SEO 缓存必须为 true 或 false。',
        'advanced_seo_cache_ttl_required' => '请输入 SEO 缓存过期时间。',
        'advanced_seo_cache_ttl_integer' => 'SEO 缓存过期时间必须为整数。',
        'advanced_seo_cache_ttl_min' => 'SEO 缓存过期时间至少为 0 秒。',
        'advanced_seo_cache_ttl_max' => 'SEO 缓存过期时间最多不能超过 14400 秒（4 小时）。',
        'seo_sitemap_cache_ttl_integer' => 'Sitemap 缓存过期时间必须为整数。',
        'seo_sitemap_cache_ttl_min' => 'Sitemap 缓存过期时间至少为 3600 秒（1 小时）。',
        'seo_sitemap_cache_ttl_max' => 'Sitemap 缓存过期时间最多不能超过 604800 秒（7 天）。',
        'debug_mode_required' => '请选择调试模式设置。',
        'debug_mode_boolean' => '调试模式必须为 true 或 false。',
        'sql_query_log_required' => '请选择 SQL 查询日志设置。',
        'sql_query_log_boolean' => 'SQL 查询日志必须为 true 或 false。',
        'outbound_proxy_required' => '请输入出站代理地址。',
        'outbound_proxy_string' => '出站代理地址必须为字符串。',
        'outbound_proxy_max' => '出站代理地址不能超过 :max 个字符。',
        'outbound_proxy_invalid' => '出站代理地址格式不正确。可用格式：:schemes（例：socks5h://127.0.0.1:1080）',
        'outbound_proxy_bypass_array' => '代理例外列表必须为数组。',
        'outbound_proxy_bypass_item_string' => '代理例外项目必须为字符串。',
        'outbound_proxy_bypass_item_max' => '代理例外项目不能超过 :max 个字符。',
        'pagination_result_cap_integer' => '总条数统计上限必须为数字。',
        'pagination_result_cap_min' => '总条数统计上限必须大于或等于 :min。（0 = 无限制）',
        'pagination_result_cap_max' => '总条数统计上限不能超过 :max。',
        'pagination_max_page_integer' => '页码上限必须为数字。',
        'pagination_max_page_min' => '页码上限必须大于或等于 :min。（0 = 无限制）',
        'pagination_max_page_max' => '页码上限不能超过 :max。',
        'core_update_github_url_invalid' => 'GitHub 仓库 URL 格式不正确。',
        'core_update_github_url_max' => 'GitHub 仓库 URL 不能超过 500 个字符。',
        'core_update_github_token_max' => 'GitHub 访问令牌不能超过 500 个字符。',
        'storage_driver_required' => '请选择存储驱动。',
        'storage_driver_invalid' => '请选择正确的存储驱动。',
        's3_bucket_max' => 'S3 存储桶名称不能超过 255 个字符。',
        's3_region_invalid' => 'S3 区域只能使用小写字母、数字和连字符。（例：ap-northeast-2，Cloudflare R2 为 auto）',
        's3_region_max' => 'S3 区域不能超过 64 个字符。',
        's3_access_key_max' => 'S3 Access Key 不能超过 255 个字符。',
        's3_secret_key_max' => 'S3 Secret Key 不能超过 255 个字符。',
        's3_url_invalid' => 'S3 URL 格式不正确。',
        's3_url_max' => 'S3 URL 不能超过 500 个字符。',
        's3_endpoint_invalid' => 'S3 端点 URL 格式不正确。',
        's3_endpoint_max' => 'S3 端点 URL 不能超过 500 个字符。',
        's3_use_path_style_boolean' => 'Path-style 地址使用设置必须为 true 或 false。',
        'driver_unusable' => "此服务器无法使用 ':driver' 驱动。:reason",
        'cache_driver_required' => '请选择缓存驱动。',
        'cache_driver_invalid' => '请选择正确的缓存驱动。',
        'redis_host_max' => 'Redis 主机不能超过 255 个字符。',
        'redis_port_integer' => 'Redis 端口必须为整数。',
        'redis_port_min' => 'Redis 端口必须大于或等于 1。',
        'redis_port_max' => 'Redis 端口不能超过 65535。',
        'redis_password_max' => 'Redis 密码不能超过 255 个字符。',
        'redis_database_integer' => 'Redis 数据库必须为整数。',
        'redis_database_min' => 'Redis 数据库必须大于或等于 0。',
        'redis_database_max' => 'Redis 数据库不能超过 15。',
        'memcached_host_max' => 'Memcached 主机不能超过 255 个字符。',
        'memcached_port_integer' => 'Memcached 端口必须为整数。',
        'memcached_port_min' => 'Memcached 端口必须大于或等于 1。',
        'memcached_port_max' => 'Memcached 端口不能超过 65535。',
        'session_driver_required' => '请选择会话驱动。',
        'session_driver_invalid' => '请选择正确的会话驱动。',
        'session_lifetime_integer' => '会话有效时长必须为整数。',
        'session_lifetime_min' => '会话有效时长至少为 1 分钟。',
        'session_lifetime_max' => '会话有效时长最多不能超过 30 天（43200 分钟）。',
        'queue_driver_required' => '请选择队列驱动。',
        'queue_driver_invalid' => '请选择正确的队列驱动。',
        'websocket_enabled_boolean' => 'WebSocket 使用设置必须为 true 或 false。',
        'websocket_app_id_required' => '使用 WebSocket 时应用 ID 为必填项。',
        'websocket_app_id_max' => 'WebSocket 应用 ID 不能超过 255 个字符。',
        'websocket_app_key_required' => '使用 WebSocket 时应用 Key 为必填项。',
        'websocket_app_key_max' => 'WebSocket 应用 Key 不能超过 255 个字符。',
        'websocket_app_secret_required' => '使用 WebSocket 时应用 Secret 为必填项。',
        'websocket_app_secret_max' => 'WebSocket 应用 Secret 不能超过 255 个字符。',
        'websocket_host_max' => 'WebSocket 主机不能超过 255 个字符。',
        'websocket_port_integer' => 'WebSocket 端口必须为整数。',
        'websocket_port_min' => 'WebSocket 端口必须大于或等于 1。',
        'websocket_port_max' => 'WebSocket 端口不能超过 65535。',
        'websocket_scheme_invalid' => '请选择正确的 WebSocket 协议。',
        'websocket_verify_ssl_boolean' => 'SSL 证书校验设置必须为 true 或 false。',
        'websocket_server_host_max' => 'WebSocket 服务器主机不能超过 255 个字符。',
        'websocket_server_port_integer' => 'WebSocket 服务器端口必须为整数。',
        'websocket_server_port_min' => 'WebSocket 服务器端口必须大于或等于 1。',
        'websocket_server_port_max' => 'WebSocket 服务器端口不能超过 65535。',
        'websocket_server_scheme_invalid' => '请选择正确的 WebSocket 服务器协议。',
        'search_engine_driver_invalid' => '请选择正确的搜索引擎驱动。',
        'log_driver_required' => '请选择日志驱动。',
        'log_driver_invalid' => '请选择正确的日志驱动。',
        'log_level_required' => '请选择日志级别。',
        'log_level_invalid' => '请选择正确的日志级别。',
        'log_days_integer' => '日志保留天数必须为整数。',
        'log_days_min' => '日志保留天数必须大于或等于 1。',
        'log_days_max' => '日志保留天数不能超过 365。',
        'public_asset_disk_invalid' => '请选择正确的公开资源磁盘。',
        's3_bucket_required' => 'S3 存储桶名称为必填项。',
        's3_access_key_required' => 'S3 Access Key 为必填项。',
        's3_secret_key_required' => 'S3 Secret Key 为必填项。',
        's3_url_url' => 'S3 URL 必须是有效的 URL。',
        'redis_host_required' => 'Redis 主机为必填项。',
        'redis_port_required' => 'Redis 端口为必填项。',
        'redis_database_required' => 'Redis 数据库编号为必填项。',
        'memcached_host_required' => 'Memcached 主机为必填项。',
        'memcached_port_required' => 'Memcached 端口为必填项。',
        'session_lifetime_required' => '会话有效时长为必填项。',
        'websocket_host_required' => 'WebSocket 主机为必填项。',
        'websocket_port_required' => 'WebSocket 端口为必填项。',
        'websocket_scheme_required' => '请选择 WebSocket 协议。',
        'identity_default_provider_string' => '默认服务商必须为字符串。',
        'identity_default_provider_max' => '默认服务商标识符不能超过 100 个字符。',
        'identity_purpose_providers_array' => '按用途划分的服务商映射必须为数组。',
        'identity_purpose_provider_string' => '按用途划分的服务商标识符必须为字符串。',
        'identity_purpose_provider_max' => '按用途划分的服务商标识符不能超过 100 个字符。',
        'identity_challenge_ttl_required' => '请输入 Challenge 过期时间。',
        'identity_challenge_ttl_integer' => 'Challenge 过期时间必须为整数。',
        'identity_challenge_ttl_min' => 'Challenge 过期时间至少为 1 分钟。',
        'identity_challenge_ttl_max' => 'Challenge 过期时间最多不能超过 1440 分钟（24 小时）。',
        'identity_max_attempts_required' => '请输入最大尝试次数。',
        'identity_max_attempts_integer' => '最大尝试次数必须为整数。',
        'identity_max_attempts_min' => '最大尝试次数至少为 1 次。',
        'identity_max_attempts_max' => '最大尝试次数最多不能超过 20 次。',
    ],
    'identity_policy' => [
        'key_required' => '请输入策略键。',
        'key_max' => '策略键不能超过 120 个字符。',
        'key_unique' => '该策略键已被使用。',
        'scope_required' => '请选择 Scope。',
        'scope_invalid' => 'Scope 必须为 route、hook、custom 之一。',
        'target_required' => '请输入 Target（路由或钩子名称）。',
        'target_max' => 'Target 不能超过 255 个字符。',
        'purpose_required' => '请选择认证用途（Purpose）。',
        'purpose_max' => '认证用途不能超过 64 个字符。',
        'provider_id_max' => '服务商标识符不能超过 64 个字符。',
        'grace_minutes_required' => '请输入 Grace 时长（分钟）。',
        'grace_minutes_integer' => 'Grace 时长必须为整数。',
        'grace_minutes_min' => 'Grace 时长必须大于或等于 0。',
        'grace_minutes_max' => 'Grace 时长不能超过 43200 分钟（30 天）。',
        'enabled_boolean' => '启用值必须为 true 或 false。',
        'priority_integer' => '优先级必须为整数。',
        'priority_min' => '优先级必须大于或等于 0。',
        'priority_max' => '优先级不能超过 65535。',
        'priority_duplicate' => '同一应用位置（:target）已存在优先级为 :priority 的启用策略。由于无法确定哪个策略先生效，请指定不同的优先级，或停用现有策略。',
        'conditions_array' => '条件（conditions）必须为数组。',
        'applies_to_required' => '请选择应用对象。',
        'applies_to_invalid' => '应用对象必须为 self、admin、both 之一。',
        'fail_mode_required' => '请选择失败模式。',
        'fail_mode_invalid' => '失败模式必须为 block 或 log_only。',
    ],
    'identity_message' => [
        'provider_not_registered' => '该 IDV 服务商尚未注册。',
        'scope_value_not_admin_policy' => '必须与运营人员添加的策略（source_type=admin）的键一致。',
        'definition_already_exists' => '相同的（provider, scope_type, scope_value）定义已存在。',
    ],
    'layout_version' => [
        'limit' => [
            'integer' => '查询条数必须为数字。',
            'min' => '查询条数必须大于或等于 1。',
            'max' => '查询条数最多为 :max 条。',
        ],
    ],
    'attributes' => [
        'ids' => 'ID 列表',
        'user_ids' => '用户 ID 列表',
        'user_id' => '用户 ID',
        'status' => '状态',
        'site_name' => '站点名称',
        'site_url' => '站点 URL',
        'site_description' => '站点说明',
        'admin_email' => '管理员邮箱',
        'timezone' => '时区',
        'language' => '语言',
        'default_language' => '默认语言',
        'identity_default_provider' => '默认服务商',
        'identity_purpose_providers' => '按用途划分的服务商',
        'identity_challenge_ttl_minutes' => 'Challenge 过期时间',
        'identity_max_attempts' => '最大尝试次数',
        'identity_policy_key' => '策略键',
        'identity_policy_scope' => 'Scope',
        'identity_policy_target' => 'Target',
        'identity_policy_purpose' => '认证用途',
        'identity_policy_provider_id' => '服务商',
        'identity_policy_grace_minutes' => 'Grace 时长（分钟）',
        'identity_policy_enabled' => '启用',
        'identity_policy_applies_to' => '应用对象',
        'identity_policy_fail_mode' => '失败模式',
        'mailer' => '邮件驱动',
        'host' => '主机',
        'port' => '端口',
        'username' => '用户名',
        'password' => '密码',
        'smtp_host' => 'SMTP 主机',
        'smtp_port' => 'SMTP 端口',
        'smtp_username' => 'SMTP 用户名',
        'smtp_password' => 'SMTP 密码',
        'encryption' => '加密',
        'from_address' => '发件人邮箱',
        'from_name' => '发件人名称',
        'max_file_size' => '最大文件大小',
        'allowed_extensions' => '允许的扩展名',
        'image_max_width' => '图片最大宽度',
        'image_max_height' => '图片最大高度',
        'image_quality' => '图片质量',
        'orphan_cleanup_enabled' => '孤立附件自动清理',
        'orphan_retention_days' => '孤立附件保留期限',
        'meta_title_suffix' => 'Meta 标题后缀',
        'meta_description' => 'Meta 说明',
        'meta_keywords' => 'Meta 关键词',
        'google_analytics_id' => 'Google Analytics ID',
        'google_site_verification' => 'Google 站点验证',
        'naver_site_verification' => 'Naver 站点验证',
        'from_version' => '起始版本',
        'to_version' => '结束版本',
        'storage_driver' => '存储驱动',
        's3_bucket' => 'S3 存储桶',
        's3_region' => 'S3 区域',
        's3_access_key' => 'S3 Access Key',
        's3_secret_key' => 'S3 Secret Key',
        's3_url' => 'S3 URL',
        's3_endpoint' => 'S3 端点 URL',
        's3_use_path_style' => '使用 Path-style 地址',
        'cache_driver' => '缓存驱动',
        'redis_host' => 'Redis 主机',
        'redis_port' => 'Redis 端口',
        'redis_password' => 'Redis 密码',
        'redis_database' => 'Redis 数据库',
        'memcached_host' => 'Memcached 主机',
        'memcached_port' => 'Memcached 端口',
        'session_driver' => '会话驱动',
        'session_lifetime' => '会话有效时长',
        'queue_driver' => '队列驱动',
        'websocket_enabled' => '使用 WebSocket',
        'websocket_app_key' => 'WebSocket 应用 Key',
        'websocket_host' => 'WebSocket 主机',
        'websocket_port' => 'WebSocket 端口',
        'websocket_scheme' => 'WebSocket 协议',
        'layout' => '布局',
        'module' => '模块',
        'token' => '令牌',
        'mailgun_domain' => 'Mailgun 域名',
        'mailgun_secret' => 'Mailgun 密钥',
        'ses_key' => 'SES 访问密钥',
        'ses_secret' => 'SES 私有密钥',
        'ses_region' => 'SES 区域',
        'mailgun_endpoint' => 'Mailgun 端点',
        'channels' => '渠道',
        'notification_channels' => '通知渠道',
        'currency' => '货币',
        'default_currency' => '默认货币',
        'maintenance_mode' => '维护模式',
        'asset_url_mode' => '资源地址方式',
        'site_logo' => '站点 Logo',
        'og_image_default' => '默认分享图片',
        'bot_user_agents' => '爬虫 User-Agent 列表',
        'bot_detection_enabled' => '使用爬虫检测',
        'bot_detection_library_enabled' => '使用爬虫检测库',
        'og_default_site_name' => 'OG 默认站点名称',
        'og_image_default_width' => 'OG 图片默认宽度',
        'og_image_default_height' => 'OG 图片默认高度',
        'twitter_default_card' => 'Twitter 默认卡片类型',
        'twitter_default_site' => 'Twitter 默认账号',
        'seo_page_cache_enabled' => '使用 SEO 页面缓存',
        'cache_ttl' => '缓存有效时长',
        'seo_page_cache_ttl' => 'SEO 页面缓存有效时长',
        'sitemap_enabled' => '使用站点地图',
        'sitemap_cache_ttl' => '站点地图缓存有效时长',
        'sitemap_urls_per_file' => '站点地图每个文件的 URL 数',
        'sitemap_gzip' => '站点地图压缩',
        'sitemap_serve_stale_on_miss' => '站点地图未生成时提供旧文件',
        'sitemap_max_urls_per_contributor' => '站点地图各项目最大 URL 数',
        'sitemap_hreflang_enabled' => '使用站点地图替代语言链接',
        'sitemap_schedule' => '站点地图自动生成周期',
        'sitemap_schedule_time' => '站点地图自动生成时刻',
        'generator_enabled' => '使用 SEO 页面生成器',
        'generator_content' => 'SEO 页面生成器内容',
        'force_https' => '强制 HTTPS',
        'login_attempt_enabled' => '登录尝试限制',
        'auth_token_lifetime' => '认证令牌有效时长',
        'max_login_attempts' => '最大登录尝试次数',
        'login_lockout_time' => '登录封禁时长',
        'password_min_length' => '密码最小长度',
        'require_password_special_char' => '密码必须含特殊字符',
        'two_factor_auth' => '两步验证',
        'allow_internal_outbound_urls' => '允许调用内网地址',
        'advanced_cache_enabled' => '使用缓存',
        'layout_cache_enabled' => '使用布局缓存',
        'layout_cache_ttl' => '布局缓存有效时长',
        'stats_cache_enabled' => '使用统计缓存',
        'stats_cache_ttl' => '统计缓存有效时长',
        'seo_cache_enabled' => '使用 SEO 缓存',
        'seo_cache_ttl' => 'SEO 缓存有效时长',
        'seo_sitemap_cache_ttl' => 'SEO 站点地图缓存有效时长',
        'debug_mode' => '调试模式',
        'sql_query_log' => 'SQL 查询日志',
        'outbound_proxy' => '出站代理地址',
        'outbound_proxy_bypass' => '代理例外列表',
        'core_update_github_url' => '核心更新 GitHub 地址',
        'core_update_github_token' => '核心更新 GitHub 令牌',
        'geoip_enabled' => '使用 GeoIP',
        'geoip_license_key' => 'GeoIP 许可密钥',
        'geoip_auto_update_enabled' => 'GeoIP 自动更新',
        'pagination_result_cap' => '列表总条数上限',
        'pagination_max_page' => '列表最大页码',
        'websocket_app_id' => 'WebSocket 应用 ID',
        'websocket_app_secret' => 'WebSocket 应用 Secret',
        'websocket_verify_ssl' => 'WebSocket SSL 证书校验',
        'websocket_server_host' => 'WebSocket 服务器主机',
        'websocket_server_port' => 'WebSocket 服务器端口',
        'websocket_server_scheme' => 'WebSocket 服务器协议',
        'search_engine_driver' => '搜索引擎驱动',
        'log_driver' => '日志驱动',
        'log_level' => '日志级别',
        'log_days' => '日志保留天数',
        'public_asset_disk' => '公开资源磁盘',
    ],
];
